README.md
The erlang_cookie and wipe_db_on_cookie_change parameters
are required for rabbitmq clustering.
=> Update cluster example to include required parameters

manifests/init.pp
W/o this patch, source for package is always being constructed
as an Internet link in case of RedHat/SUSE.
This is a problem as we may want to use no source in case of
yum provider.
The solution is to not construct the real_package_source for yum
provider and use it as is.
Closes-bug: #MODULES-1631
=> Do not enforce the source value for yum provider

README.md, lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb, lib/puppet/type/rabbitmq_binding.rb, lib/puppet/type/rabbitmq_queue.rb, spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_queue/rabbitmqadmin_spec.rb, spec/unit/puppet/type/rabbitmq_binding_spec.rb, spec/unit/puppet/type/rabbitmq_queue_spec.rb
I Add the two new resources ``rabbitmq_queue`` and ``rabbitmq_binding``.
So it will be also possible to manage queues and bindings between queue and exchange with puppet.
=> Add new Resources for Queue and Bindings.

lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb
I found that RabbitMQ 3.3.4 separates tags with only a space, where 3.3.5 separates them with a comma and then a space. This works around that by first splitting tags by spaces, then stripping any word-final commas if they are present, so that it will work regardless of which way rabbitmqctl formats the tag list.
This has already been tested throughout my company's various environments, and all tests pass after this change.
=> User tag changes for <=3.3.4

manifests/repo/apt.pp
Since the default value of package_apt_pin is an empty string
rather than a boolean, it was failing the conditional test in
Puppet 3.7+. This commit changes the conditional to check for an
empty string.
=> Fix pin conditional

lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb, lib/puppet/provider/rabbitmq_policy/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_user_permissions/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_vhost/rabbitmqctl.rb, lib/puppet/provider/rabbitmqctl.rb, spec/unit/puppet/provider/rabbitmq_plugin/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_user_permissions/rabbitmqctl_spec.rb
W/o this fix, then RabbitMQ put in a cluster and managed,
for example, by Pacemaker, rabbitmqctl/rabbitmqadmin commands
could fail due to cluster is not ready yet.
The solution is:
1) Add a run_with_retries method to the existing Rabbitmqctl class
as a retry decorator to ensure the commands will retry instead
of fail then the cluster is not ready.
2) Derive the providers from the former one to make
them able to retry all of the list_* commands and, as a result,
to wait for RabbitMQ ready as well.
3) Update rspecs. Add missing rspec for rabbitmq_plugin
Co-authors:
Dmitry Ilyin <dilyin@mirantis.com>,
Colleen Murphy <colleen@puppetlabs.com>
Closes-bug: #MODULES-1452
=> Make rabbitmq providers to retry the commands

README.md
Due to the way the environment configuration works setting ssl_true does not actually disable the plaintext listener.  The tcp_listeners in the config are properly removed, but the RABBITMQ_NODE_PORT=5672 environment variable is still set which overrides the config file option and still starts up the plaintext listener on port 5672. 
Fixing the code to properly disable the env variable is most likely the "better" solution, but this workaround is simple and now documented
=> Documentation update for ssl_only

manifests/install/rabbitmqadmin.pp
W/o this patch, Rabbitmq::Install::Rabbitmqadmin/Staging::File[rabbitmqadmin]
/Exec[/var/lib/rabbitmq/rabbitmqadmin]
sometimes could fail the curl command due to transient or connectivity errors.
The solution is:
- For transient errors:
* use timeout param for staging::file
* use --retries , --retry-delay flag for curl command passed to staging::file
- For connectivity errors:
* improve staging module to retry its commands as well, see
https://github.com/nanliu/puppet-staging/pull/52
Closes-bug: #MODULES-1650
=> Add retries for non transient file transfer errors

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
This commit adds the ssl_versions parameter. This allows users to
choose which versions of SSL that RabbitMQ should accept.
=> Added ssl_versions parameter

README.md, manifests/config.pp, spec/classes/rabbitmq_spec.rb
W/o this patch, env parameters from rabbitmq-env.conf
will always override the ones specified at the init file of
rabbitmq-server.
This is an issue as we may want them to differ
for separated rabbitmq instances running at the same host.
The soution is to remove RABBIT(MQ)_ prefixes for all
parameters in rabbitmq-env.conf as it described at the
man pages.
Closes-bug: #MODULES-1673
=> Fix rabbitmq-env.conf parameters

templates/rabbitmqadmin.conf.erb
This fixes MODULES-1691, caused by upstream bug
https://github.com/rabbitmq/rabbitmq-management/issues/20
=> SSL option in rabbitmqadmin.conf is broken

spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
RabbitMQ was not respecting this setting. The format of the configuration file was incorrect. This patch updates to bring this in line with documentation.
The format reference example is given in https://www.rabbitmq.com/ssl.html#disabling-tls-versions
Also add version list for rabbitmq_management config ssl_opts.
=> Bugfix for ssl_versions in rabbitmq.config 

manifests/config.pp
LDAP related variables in rabbitmq.config.erb rely
on dynamic scoping, which is discontinued in the future parser.
They need to be exposed in rabbitmq::config in order to be
accessible in the template.
=> Fix unscoped template variables

lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb, lib/puppet/type/rabbitmq_user.rb, spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_user_spec.rb
Hello,
second attempt. The commit messages should contain enough info.
provider rabbitmq_user
* do not expose the administrator tag
type rabbitmq_user
* do not allow explicit setting of the administrator tag
* default to an empty array of tags
* sort tags before comparison
Let me know if you have any comment.
Thanks,
Arne
=> administrator and tags fixes

manifests/params.pp
rabbitmq::repo::apt tests whether this value is true,
which fails with the future parser if default is the
empty string.
=> Make $rabbitmq::params::package_apt_pin default to undef

spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
Fixed layout of ssl_options section to make sure they are on separate
lines, making it easier to read when the file is cat'ed.
=> Fixed up rabbitmq.conf file layout

README.md, lib/puppet/provider/rabbitmq_erlang_cookie/ruby.rb, lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb, lib/puppet/type/rabbitmq_erlang_cookie.rb, manifests/config.pp, manifests/init.pp, manifests/install/rabbitmqadmin.pp, manifests/params.pp, spec/unit/puppet/provider/rabbitmq_exchange/rabbitmqadmin_spec.rb
This is a two commits pull request, the majority is in order to add support for OpenBSD.
The other smaller part, that I ran into after getting the module to work, is to fix lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb.
Both explained below.
To support OpenBSD, in the manifests/params.pp, add some more variables, esp. for the rabbitmq_home directory, the rabbitmq system user and group, and additionally make the $plugin_dir OS/Distribution dependent. Then use the new variables throughout the other manifests, where the hardcoded versions were used before.
Further in manifests/init.pp, the dependency of Class['::rabbitmq::install::rabbitmqadmin'] -> Rabbitmq_exchange<| |> is moved up into the if $admin_enable part, since it will throw an error, if rabbitmq admin is not enabled.
In …
=> Add Support for OpenBSD and fix rabbitmq_exchange/rabbitmqadmin.rb

spec/acceptance/zz281_spec.rb, spec/classes/rabbitmq_spec.rb
The Gemfile is now pulling in rspec-core 3.2.2 & rspec-puppet 2.0.1.
This fix has updated the tests to ensure they pass using these versions.
=> MODULES-1857 - Fixing test failures

manifests/config.pp
https://tickets.puppetlabs.com/browse/MODULES-1888
If future parser is enabled this will fix an issue where we're calling two variables that are not scoped in the rabbitmq::config class which calls the rabbitmq.conf.
=> MODULES-1888 - Added missing config params used in the rabbitmq.conf template.

manifests/config.pp
This was added twice in two separate pull requests and
causes the following error:
Error: Cannot reassign variable ssl_interface at /etc/puppet/modules/rabbitmq/manifests/config.pp:35
=> Remove duplicate $ssl_interface

manifests/config.pp
If the admin service isn't enabled then we shouldn't create the config
file.
This caused an issue for us because any changes to any resources in rabbitmq::config will cause rabbit to be restarted.  We had intentionally disabled admin when moving to a newer version of the module, because we were trying to avoid restarting rabbit at the time.  Due to this file being created, we had rabbit restarts due to a feature we had explicitly disabled.
=> Don't create rabbitmqadmin.conf if disabled

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
This patch adds optional array parameter 'ssl_ciphers' which go into rabbitmq's config if SSL is enabled and limit the ciphers to the specified list.
Documentation is erlang as these parameters are passed through: http://www.erlang.org/doc/man/ssl.html
Supported ciphers can be listed with: rabbitmqctl eval 'ssl:cipher_suites().'
Functionality can be tested with something like Cipherscan: https://github.com/jvehent/cipherscan.git
=> Add support for SSL Cipher lists

lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb
Old one was failing with:
Error: Execution of '/usr/sbin/rabbitmqctl eval rabbit_auth_backend_internal:check_user_login(<<"root">>, [{password, <<"pass">>}]).' returned 2: Error: {undef,
[{rabbit_auth_backend_internal,check_user_login,
[<<"root">>,[{password,<<"pass">>}]],
[]},
{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,569}]},
{rpc,'-handle_call_call/6-fun-0-',5,
[{file,"rpc.erl"},{line,205}]}]}
rabbitmq-server                     3.5.0-1
=> Fix check_password function and use the standard rabbitmq api call instead

manifests/init.pp
provider is not a meta parameter and not defined as a parameter in rabbitmq_plugin type - this causes failed executing when installing plugins defined in init.pp. Seems to function just by removing the provider param. Either need to do this or fix the type.
Adam
=> provider is not a metaparameter

lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
When using set_policy to define the 'expires' policy, or setting 'ha-params'
when using 'ha-mode' 'exactly', the rabbitmqctl provider passes a stringified
numeric value to the `rabbitmqctl set_policy' invocation. In turn, this one
chokes on the values and throws the following error:
err: ...
set_policy -p vhost --priority 0 --apply-to queues expire_queues ^rpc_.* {"expires":"1800000"}' returned 2:
Setting policy "expire_queues" for pattern "^rtcp_.*" to "{\"expires\":\"1800000\"}" with priority "0"
...
<<"1800000">> is not a valid queue expiry
This is with puppet 2.7.
I'm not 100% sure why this happens - it seems the a hash is passed all-strings
down to the type/provider in 2.7? Even if in the manifest file, a numeric
value is used. Hum?
82     rabbitmq_policy { 'expire_queues@vhost':
83 …
=> set_policy: convert known parameters to integers

manifests/config.pp, spec/classes/rabbitmq_spec.rb
Running RHEL 7.1 with 'yum' or 'rpm' provider, puppetlabs-rabbitmq is not
idempotent.
After a second run, puppet tries to change the SElinux context:
<code>/File[/etc/systemd/system/rabbitmq-server.service.d]/seltype: seltype
changed 'rabbitmq_unit_file_t' to 'systemd_unit_file_t'</code>
Since packaging already manages SElinux labels, we should not let Puppet
doing it (default behavior).
This patch aims to set selinux_ignore_defaults to True for the File
resource (/etc/systemd/system/rabbitmq-server.service.d).
Thanks to that patch, Puppet will be indempotent between all runs on
RHEL platforms.
=> Ensure idempotency between Puppet runs

.fixtures.yml, README.md, spec/spec_helper_acceptance.rb
I think changing myhost to myvhost in the README.md makes it much clearer because myvhost is self-describing, whereas myhost is ambiguous describing potentially a hostname. This kind of bit me when setting up a ha policy, and would've been much clearer if i saw the distinction "vhost".
=> add some clarity to README.md

README.md, metadata.json
Once puppetlabs-apt 2.1.0 is released (2015-06-16) the postgresql module
will be compatible with apt 1.x (>= 1.8.0) and 2.x (>= 2.1.0). This will
*not* work with puppetlabs-apt 2.0.x.
=> Loosen the apt dependency

spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
Fixed up how the template file generates the rabbitmq_mangement section
for rabbitmq.conf. Making its easier to read when you cat the generated
file on an agent, by correctly indenting and newlining configuration
parameters.
Also updated the rspec test to reflect the changes in the file contents.
=> Fixed up syntax for rabbitmq_management section in rabbitmq.conf

lib/puppet/provider/rabbitmq_erlang_cookie/ruby.rb
change separator from “:” to “/“ to generate proper dirname to allow
removal
=> (MODULES-1987) mnesia dir is not wiped out

README.md, manifests/config.pp, spec/classes/rabbitmq_spec.rb
When deploying RabbitMQ in cluster with Pacemaker, we don't want to let
Puppet to manage the cluster so we configure it without clustering options.
Though we need to configure the Erlang Cookie in all RabbitMQ nodes.
This patch aims to:
* allow to configure the cookie without config_cluster boolean at True
* keeps backward compatibility, it will try to install the cookie if the
config_cluster is at True only (so it won't wail for deployment with
defaults values).
* we try to create the cookie only if it's not set to 'undef'.
* update README about new usage
* add rspec tests to test all possible cases.
=> Allow to manage Erlang Cookie without config_cluster

manifests/repo/apt.pp, metadata.json, spec/classes/rabbitmq_spec.rb
Using the latest version of puppetlabs-apt and the latest of puppetlabs-rabbitmq I get the following : 
Invalid parameter include_src on Apt::Source[rabbitmq] at /etc/puppet/environments/testing/modules/rabbitmq/manifests/repo/apt.pp:32 on node xxxxxx
This PR fix the error.
See : https://tickets.puppetlabs.com/browse/MODULES-2177
=> Fix "Invalid parameter include_src on Apt::Source[rabbitmq]"

manifests/repo/apt.pp, metadata.json, spec/classes/rabbitmq_spec.rb
This reverts commit 8587867ce9596201da22845cff57af003b4a7a07.
puppetlabs-apt 2.1.0 re-introduced the include_src parameter to avoid
breaking changes like this.
/cc @Pryz @cmurphy
=> Revert "(MODULES-2177) Change apt::source for new apt module"

lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
When setting message-ttl or max-length policies using rabbbitmq_policy
type the puppet execution fails because these two parameters are
passed as strings instead of integers to rabbitmqctl. This patch adds
the code to convert these two values to integer before using them.
=> (MODULES-2372) Convert message-ttl and max-length to integer

manifests/config.pp, spec/classes/rabbitmq_spec.rb
It is possible for the RabbitMQ service to be managed by something
other than systemd on EL7.  An example is when pacemaker is managing
RabbitMQ in an HA cluster.  In this use case, the systemd limits will
have no effect, but it is still desirable to set the file descriptor
limit.
=> Install file limits snippet to limits.d on EL7

manifests/params.pp
The RabbitMQ Stomp Plugin documents the default listening port
to be 61613. With the SSL equivalent being 61614. We should
probably be following the de facto standard.
=> Optional correction for default stomp ports

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, templates/rabbitmq.config.erb
This PR adds a parameter to configure only the SSL port for STOMP plugin.
I've added related parameter doc in README.md. I didn't add tests because there are very few tests about stomp and none about ssl_stomp_port.
=> Add parameter to configure only the SSL port for STOMP plugin

.travis.yml, README.md, lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb, lib/puppet/type/rabbitmq_parameter.rb, spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_parameter_spec.rb
This addresses [MODULES-2281] as it adds support to use the set_parameter command line option to rabbitmqctl. The set_parameter command line option can be used to configure a static shovel.
~~~puppet
rabbitmq_parameter { 'documentumShovel@/':
component_name => '',
value          => {
'src-uri'    => 'amqp://',
'src-queue'  => 'my-queue',
'dest-uri'   => 'amqp://remote-server',
'dest-queue' => 'another-queue',
},
}
~~~
=> Adds support for rabbitmqctl command option set_parameter

manifests/params.pp
This is a reasonable change, but is backwards incompatible and will
cause configuration changes.
Undoes #385
=> Revert #385

CHANGELOG.md, metadata.json
5.3.0 was already released and then deleted, but there is no git history.
=> Release 5.3.1

lib/puppet/provider/rabbitmqctl.rb
This addresses the issue at: https://tickets.puppetlabs.com/browse/MODULES-2252  - we experienced this issue at various occasions, and seems to mostly occur when the server in question is under high load. The `Timeout` exception caught in the `rabbitmqctl.rb` provider is not being caught correctly, leading to all RabbitMQ resources not being retried, and timing out with a generic `execution expired` message.
I've confirmed this change in our PRD and STG environments, and it improves the situation - we've not experienced another resource timeout since making this change.
=> MODULES-2252 - fix "Command execution expired" issue

README.md
Change option description from disk to disc, as the actual parameter value needs to be "disc" or "ram"
=> Change cluster_node_type description in Readme.md - MODULES-2786

README.md
1. Put spaces after headings so it's more readable in plain text.
2. Set Puppet code type in an example.
=> (MAINT) Fix README styling

lib/puppet/provider/rabbitmq_erlang_cookie/ruby.rb
This fixes an issue with the latest version of puppet when run from a cron job, which does not include "/opt/puppetlabs/bin" in the PATH that the cron jobs see. The other issue with the current implementation is that, in the latest puppet code at least, the custom_environment that's being set in the block given to `has_command` is not used when resolving the location of the command.
To reproduce the issue, run `PATH=/usr/bin:/bin sudo /opt/puppetlabs/bin/puppet agent --test`
=> Fix incompatability with latest puppet

manifests/params.pp, spec/classes/rabbitmq_spec.rb
I noticed that with `epel` enabled, `yum` can resolve the erlang dependencies of rabbitmq without the help of additional puppet erlang modules on CentOs7. Since `epel` is needed on both CentOS and RedHat, maybe its safe to use `yum` as the package provider for them instead of `rpm`.
=> Use yum as package provider for RedHat

manifests/init.pp, spec/classes/rabbitmq_spec.rb
(This is another try at implementing #400 . AFAIK github doesn't allow pull request amendment by a different person so i'm sending a new pull request.)
Previously errors were thrown when $file_limit was integer, as
validate_re() function only works with strings. $file_limit
is now casted to string before passing it to validate_re().
=> Allow integer values for $file_limit

lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb
Skips federated exchanges in the output, as these have a different set of fields, and cause issues when they're parsed.
=> MODULES-2252 - fix "Could not prefetch rabbitmq_exchange provider 'rabbitmqadmin': 757: unexpected token at 'fanout'" issue

lib/puppet/type/rabbitmq_policy.rb
Hello,
I was using this module to create a policy and was stumped why `create_resources` wasn't working with something like the following mock hiera data:
```
queue-limit@vhost:
pattern: '^foobar$'
priority: 1
applyto: 'queues'
definition:
'max-length': 1000000
```
I received the following errors in my puppet run:
```
puppet-agent[26841]: Failed to apply catalog: Parameter definition failed on Rabbitmq_policy[queue-limit@vhost]: Invalid definition
puppet-agent[26841]: Wrapped exception:
puppet-agent[26841]: Invalid definition
puppet-agent[26841]: Wrapped exception:
puppet-agent[26841]: Invalid definition
```
This change makes the error message for non-string definition values more verbose.
I did not make a ticket for this as it is (what I would consider to be) cosmetic and not vital to …
=> Better error when policy definition value is not a string

manifests/repo/apt.pp, spec/classes/rabbitmq_spec.rb
APT pinning can use 4 digit values. How it was done it was pinning all rabbitmq-server packages (even those provided by other origins) this should fix it to the point that only packages provided by www.rabbitmq.com will be pinned
=> Fixing pinning for apt on Debian based distros

manifests/repo/apt.pp
I needed 3.6.0 version for rabbitmq, which was handled by custom debian repo, but no apt-update was done after. I was then stuck at 3.3.5.
=> Ensure an apt-update after change repository so we can get upstream version

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
(#MODULE-2040) -Add auth_backends Variable
The current implementation of auth_backends forces configuration of auth_backends to either the RabbitMQ default or a hardcoded configuration for LDAP. This variable allows configuration to be controlled as desired, particularly, the case of interest to myself: it will allow for a configuration where LDAP is used to authenticate and the RabbitMQ mnesia database is used for authorizations. The change is backwards compatible and has a test.
=> Module2940 addition auth backends variable

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
Allow to configure the parameters like rabbitmq_management.rates_mode,
which are important for production use and high loaded systems.
Closes-bug: #MODULES-2754
=> Add the config_rabbitmq_management_variables param

manifests/install/rabbitmqadmin.pp, spec/classes/rabbitmq_spec.rb
When trying to get rabbitmqadmin the manifest
sends request to localhost which is wrong since
node_ip_address can differ.
=> Fix rabbitmqadmin url

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
Added the rabbitmq config option `heartbeat` to provide a heartbeat
connection to nodes. By default this option isnt set in rabbitmq.conf
and its package default is 580 seconds, if the option is set, the config
will reflect this change. There are no other config changes required.
Spec tests provided.
=> Added heartbeat option to rabbitmq-server

manifests/params.pp, spec/classes/rabbitmq_spec.rb
It is dangerous to not use https for importing gpg keys
from web sources. This shoud be https and not http.
Signed-off-by: Jordan Conway <jconway@linuxfoundation.org>
=> Update default $package_gpg_key to https

manifests/install/rabbitmqadmin.pp
We currently hardcoded it to localhost which will still cause issues
when rabbitmq tries to connect to an ip which isn't listening on
localhost for various reasons.
This improvement will make sure that our curl operation always matches
the current ip address used by rabbitmq
=> curl --noproxy value should be dynamically set

lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb, lib/puppet/type/rabbitmq_plugin.rb, spec/unit/puppet/type/rabbitmq_plugin_spec.rb
The file /etc/rabbitmq/enabled_plugins should to be owned by root and
world readable.  To ensure this happens, this module needs to ignore
the system wide umask whenever it recreates the file.  This then
sidesteps the scenario where a rabbitmq process, running under a
separate daemon account, is no longer able to access its own file.
=> Ignore system umask when generating enabled_plugins file.

lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb
An error similar as #412, skips federated queues in the output.
=> fix federation queue for error: Could not prefetch rabbitmq_queue provider 'rabbitmqadmin': 757: unexpected token

.fixtures.yml, README.md, metadata.json
voxpupuli is the namespace supported by Puppetlabs community, we should
use this repository instead of the fork.
=> Replace nanliu-staging by voxpupuli-staging

manifests/install/rabbitmqadmin.pp, spec/classes/rabbitmq_spec.rb
(1) If node_ip_address is an IPv6, we need to pass specific options to curl
so staging module can work.
When using IPv6, curl needs to be used with specific options, for
example with localhost:
```curl -g -6 [::1]```
(2) Sanitize node_ip_address if IPv6
node_ip_address is used bu rabbitmqadmin.pp and also in config.pp for
rabbitmqenv.config. This parameter should not be given with brackets,
otherwise RabbitMQ won't start.
Though when using curl, we need the add the brackets so this patch makes
sure the brackets are added to node_ip_address if it's an IPv6 so curl
will work correctly.
=> rabbitmqadmin: bring ipv6 support

templates/rabbitmq.config.erb
Following this commit 8f75ff5cfea7945a0d6a4074184a7279a81349d4, if one
use this simple manifest:
```puppet
class { 'rabbitmq':
admin_enable   => true,
service_manage => true,
}
```
Then two blocks of
```
{rabbitmq_management, [
]}
```
gets created.
The problem is that only the parameters of the first block is taken into
account.
Furthermore the /first/ block is *always* created.  The template has:
```
+<% if @config_management_variables -%>,
+  {rabbitmq_management, [
+    <%= @config_management_variables.sort.map{|k,v| "{#{k}, #{v}}"}.join(",\n    ") %>
+  ]}
+<%- end -%>
```
and config_management_variables is set to `{}` with is not `false`.
This is an attempt to fix this and keep the same behavior.
=> rabbitmq_management block is created twice.

README.md, manifests/install/rabbitmqadmin.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
The support for IPv6 address for `rabbitmqadmin` is non-working leading
to this error:
```
Debug: Exec[/var/lib/rabbitmq/rabbitmqadmin](provider=posix): Executing 'curl -k --noproxy -g -6 [::1] --retry 30 --retry-delay 6 -f -L -o /var/lib/rabbitmq/rabbitmqadmin "https://guest:guest@[::1]:15671/cli/rabbitmqadmin"'
Debug: Executing 'curl -k --noproxy -g -6 [::1] --retry 30 --retry-delay 6 -f -L -o /var/lib/rabbitmq/rabbitmqadmin "https://guest:guest@[::1]:15671/cli/rabbitmqadmin"'
Notice: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/Staging::File[rabbitmqadmin]/Exec[/var/lib/rabbitmq/rabbitmqadmin]/returns: curl: (3) [globbing] illegal character in range specification at pos 2
Notice: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/Staging::File[rabbitmqadmin]/Exec[/var/lib/rabbitmq/rabbitmqa …
```
=> Rabbitmqadmin IPv6 non-working.

templates/rabbitmq.config.erb
Observed with Puppet 3.8.6 on OpenBSD.
When the parameter is not specified, then 'UNSET' will end
up in the rabbitmq.conf preventing it from starting up.
I don't want to specify it, but I use hiera, so I cannot set
the parameter as undef, which would be taken as string.
Setting the parameter to false, will not get past the
validate_string()
because of that, update the template to check if node_ip_address != 'UNSET'
and only then add it to the resulting file
=> Merge of pull #444 breaks rabbitmq for me.

.fixtures.yml, README.md, metadata.json, spec/spec_helper_acceptance.rb
1.0.4 was tagged a while ago but never pushed to their namespace. This
needs to be nanliu until it is pushed to the forge.
=> puppet-staging is not yet published

lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
Change `rabbitmq_policy` type to pass the policy definition value `shards-per-node` as an integer instead of a string to `rabbitmqctl`, as required by the [rabbitmq-sharding](https://github.com/rabbitmq/rabbitmq-sharding) plugin.
=> MODULES-3148: Allow shards-per-node for rabbitmq_policy definition to be integer

lib/puppet/type/rabbitmq_parameter.rb
When attempting to specify add-forward-headers to a rabbitmq shovel parameter, the rabbitmq_parameter type limits input to strings, but the rabbitmqctl command requires a boolean type.
Without the patch, add-forward-headers raises the ArgumentError when a boolean is specified:
```Error: Failed to apply catalog: Parameter value failed on Rabbitmq_parameter[testhost@testvhost]: Invalid value at shovel_queue.pp:27```
Without the patch, add-forward-headers as a string type raises an error in rabbitmqctl:
```
Error: Validation failed
add-forward-headers should be boolean, actually was <<"false">>
```
This PR allows boolean types to be used in the value attribute when using the rabbitmq_parameter resource.
=> Bugfix rabbitmq_parameter type check for add-forward-headers.  Requires boolean.

manifests/init.pp
Missing ::params for the $config_management_variables variable within init.pp.
=> Properly inherit config_management_variables from params

manifests/install/rabbitmqadmin.pp, spec/classes/rabbitmq_spec.rb
Fix an issue when $node_ip_address is 'UNSET'. Also, make curly-braces for conditionals consistent (and follow the style that I believe is used in puppet style guide).
See https://tickets.puppetlabs.com/browse/MODULES-3098  and 
https://github.com/puppetlabs/puppetlabs-rabbitmq/commit/33dfa95535910424974734f195466d5a804474f9
I did some basic testing, but should be tested some more for corner cases.
Also note that is_ipv6_address was introduced 2 months ago, so will cause problems for anyone with an older stdlib; if we wanted a simpler version, here's a patch against the commit above that I think will also work.
[rabbitmqadmin.pp.patch.txt](https://github.com/puppetlabs/puppetlabs-rabbitmq/files/178400/rabbitmqadmin.pp.patch.txt)
stdlib.
=> Fix an issue when $node_ip_address is 'UNSET'.

manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, spec/spec_helper_local.rb
OpenBSD doesn't need to set a source for the package installation.
Add some spec tests for this particular OpenBSD case.
This makes it work for me as expected/intended.
=> Unbreak package installation on OpenBSD.

lib/puppet/type/rabbitmq_user.rb
Change the log output to not include the user's password, as many places don't want their passwords in logs. This was already done for actual runs, but not --noop runs.
Output before was:
```
Rabbitmq_user[demo]/password: current_value , should be SecretPassword (noop)
```
Output now is:
```
Rabbitmq_user[demo]/password: current_value , should be <new password> (noop)
```
I don't have a corresponding spec for this, unfortunately. I played with rspec-puppet for a while but couldn't find a way to trap the output generated by puppet itself in order to assert against it. I would appreciate help in doing so.
=> Don't show new user password changes on noop runs

manifests/init.pp
This warning is not needed in any reasonable scenario and
blocks users from disabling ssl wthout warnings.
Closes #465
=> (MODULES-3295) Allow ssl => false without warning

manifests/repo/apt.pp
It's useful to be able to set this parameter on `apt::source`.
I've defaulted this param to `undef` which is the same as the default in `apt::source`.
=> Allow passing architecture to `apt::source`

lib/facter/rabbitmq_nodename.rb, spec/unit/rabbitmq_nodename_spec.rb
With certain platforms, the nodename is quoted resulting in a NilClass
error.  In addition, the regex does not properly match if a nodename
has dashes.  This commit resolves these issues.
=> Improve robustness of rabbitmq_nodename

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
This allows us to add additional config variables to the end of the rabbitmq.conf file - this is useful for adding generic plugin config, for example.
=> Add additional config variables

manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
MODULES-3570 Rabbitmq config tcp options and collect statistics interval tuning
* Add parameters to tune the rabbitmq tcp options.
* Add collect statistics interval parameter to configure the management plugin
This paramter can help increase the performance of rabbitmq by reducing load
on rabbit with stats collections.
=> Add tcp parameters and stats collect config

templates/rabbitmq.config.erb
We've noticed changes in our RabbitMQ infrastructure after upgrading  Puppet module to the latest forge release, tcp_listen_options were added to RabbitMQ configuration template. Unfortunately, one option was missing and it changes significantly on how broker terminates connections after heartbeat has expired - instead of previous behaviour of sending RST,ACK it starts sending FIN,ACKs instead causing libraries that don't have good exception handling or they aren't using publisher confirms options for publishing messages to start losing messages.
Adding this directive as per https://github.com/rabbitmq/rabbitmq-server/blob/master/src/rabbit.app.src as it's listed as default but not documented on RabbitMQ website.
=> (MODULES-3740) Adding missing undocumented rabbitmq tcp_listen_options directive

lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb
On overloaded or slow systems after service starting there could be some temporary issues with requests to rabbit-server. To avoid such situations `run_with_retries` should also be used for checking password.
=> run "check_password" with retries

lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb
May be other cases, but wanted to fix this one outside of a feature request...
unless(source_name.empty?) seems a little cleaner / more idiomatic.
=> use unless instead of if, and empty? instead of !=''

manifests/init.pp
This param is checked in install.pp:
https://github.com/puppetlabs/puppetlabs-rabbitmq/blob/master/manifests/install.pp#L19
The check doesn't work if the variable contains empty string.
=> set $real_package_source to undef instead of empty

.sync.yml
This allows deprecation errors in the module without resulting in failures.
=> Allows deprecation errors

spec/unit/puppet/type/rabbitmq_binding_spec.rb, spec/unit/puppet/type/rabbitmq_exchange_spec.rb, spec/unit/puppet/type/rabbitmq_parameter_spec.rb, spec/unit/puppet/type/rabbitmq_plugin_spec.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb, spec/unit/puppet/type/rabbitmq_queue_spec.rb, spec/unit/puppet/type/rabbitmq_user_permissions_spec.rb, spec/unit/puppet/type/rabbitmq_user_spec.rb, spec/unit/puppet/type/rabbitmq_vhost_spec.rb
the parallel_spec that is run on travis revealed a dependency issue in the user_permissions_spec. none of the type unit tests were using the spec_helper and were requiring puppet and their respective types explicitly. this reverses that by requiring the spec_helper and removing the other dependencies and in turn repairing the failures.
this is causing travis to fail needlessly on all PRs currently.
=> (maint) parallel_spec maintenance: spec_helper

README.md, manifests/config.pp, manifests/init.pp, manifests/params.pp, templates/rabbitmq.config.erb
Add the option to provide the "depth" configuration option in the rabbitmq.config for SSL validation depth.
Puppetlabs ticket MODULES-4408
=> added ssl_depth and password params for configuration

templates/rabbitmq.config.erb
As per a recent commit [1], the default value of ssl_depth is undef.
This turned out problematic, as the template checks for 'UNSET', and
validation of this parameter is only done if the ssl_depth was set to
something (remember it defaults to undef). So, using the default value
results in an invalid rabbitmq configuration, which breaks with a syntax
error.
This sets the check in the template to work only if the value of that
variable is set (so it won't write it if the default undef is used).
[1] https://github.com/puppetlabs/puppetlabs-rabbitmq/commit/21ac01e4a1835604e9ffaaedbef024fd2ea9a0f4
=> [MODULES-4450] don't set ssl depth if undef

manifests/config.pp, spec/classes/rabbitmq_spec.rb
These options are used for RabbitMQ to create a TCP listener, which is
not something we want if we are doing SSL-only. So these are not used as
defaults if that option is set.
=> [MODULES-4223] don't set NODE_PORT and NODE_IP_ADDRESS if ssl_only

manifests/init.pp
based on: https://www.rabbitmq.com/ssl.html
the depth option has to be an integer
=> [Bugfix] convert $ssl_depth from string to integer

spec/classes/rabbitmq_spec.rb, templates/rabbitmqadmin.conf.erb
This PR fixes the issue, that when a recent RabbitMQ package is installed, the rabbitmqadmin fails to handle exchanges correctly if SSL is enabled and results in an error.
Therefore the `rabbitmqadmin.conf` template is extended with SSL options to match the CLI arguments of the rabbitmqadmin tool. In version 3.6.2 of the [rabbitmq-management](https://github.com/rabbitmq/rabbitmq-management) package, the admin tool changes its SSL support and incorporates new SSL arguments when communicating with the RabbitMQ server.  Alternatively the admin tool reads the arguments from a config file.
This config file is used as argument when instrumenting the rabbitmqadmin tool via this Puppet module (when declaring exchanges). The SSL options are only written to the config file when SSL is enabled. In …
=> Extend rabbitmqadmin config template with SSL options.

lib/puppet/provider/rabbitmq_erlang_cookie/ruby.rb
Change `rabbitmq_erlang_cookie` provider to call the puppet API instead of the puppet binary.
=> [MODULES-3733] rabbitmq provider env_path does not locate ruby gem installed puppet binary

manifests/repo/apt.pp, spec/classes/rabbitmq_spec.rb
Puppetlabs Apt module now has deprecation warnings when call in the manner being used by the puppetlabs rabbitmq module. Updated and tested against puppetlabs apt module 2.2.2
=> Updated app.pp to address deprecation warnings

templates/rabbitmq.config.erb
This looks up the `config_variables` input parameter using `scope` in the `rabbitmq.config.erb` template so that it works with Puppet 4.
=> Scope config_variables for Puppet 4

spec/classes/rabbitmq_spec.rb, spec/spec_helper_local.rb
This makes things a bit more consistent, and also fixes test failures
due to newer puppetlabs-apt module requiring items under $facts['os']
=> Improve distro fact handling in tests

manifests/config.pp
This basically copies CentOS approach and increases Ubuntu 16.04 compatibility by creating /etc/systemd/system/rabbitmq-server.service.d/limits.conf file
=> Systemd open files limit

lib/facter/rabbitmq_nodename.rb, spec/unit/rabbitmq_nodename_spec.rb
rabbitmqctl status returns node status without trailing points
on rabbitmq: 3.6.10, e.g:
root@rabbitmq:~# rabbitmqctl status
Status of node rabbit@rabbitmq
[{pid,16527},
....
So let's align regexp as well
=> Update regexp for rabbitmq_nodename fact

manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/inetrc.erb
This adds a new parameter, ipv6, which if set to true will configure
the erlang runtime to use IPv6 for distribution and name resolution.
It also adds two other parameters, inetrc_config and
inetrc_config_path, which support ipv6 enablement.
The environment variable ERL_INETRC is set to the value of
inetrc_config_path, by default /etc/rabbitmq/inetrc.  If ipv6 is
disabled (default), this file is empty and has no effect.  If ipv6 is
enabled, it sets the option 'inet6' to 'true', which prefers IPv6 name
resolution[1].
Users may pass their own inetrc_config to supply an alternate
template.
In addition, if ipv6 is set to true, the flag '-proto_dist inet6_tcp'
is appended to the environment variables RABBITMQ_SERVER_ERL_ARGS and
RABBITMQ_CTL_ERL_ARGS.  This enables IPv6 as the distribution …
=> Add options for IPv6 and inetrc

lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb
This is more idiomatic ruby, avoids creating array only to throw it away, and consistent with a method below.
=> Simplify "all_vhosts" in rabbitmq_queue provider

lib/puppet/provider/rabbitmq_vhost/rabbitmqctl.rb
Just a small thing that threw me when looking through the code.
This provider is definitely calling `rabbitmqctl -q list_vhosts`, so if that output can't be parsed it should complain about invalid vhost lines, rather than invalid user lines.
Looks like a copy-paste error from other similar providers.
This will improve user experience when they encounter this error.
=> Fix error text in `rabbitmq_vhost` provider

spec/spec_helper_acceptance.rb
when running the non-Docker Beaker acceptance tests, I get the following error:
```
Failure/Error: on host, "/bin/touch #{default['puppetpath']}/hiera.yaml"
Beaker::Host::CommandFailure:
Host 'centos-7-x64' exited with 1 running:
/bin/touch /etc/puppet/hiera.yaml
Last 10 lines of output were:
```
It seems like with the new images, this may not be necessary anyway (I have a `hiera.yaml` file already), and for some reason, running `bundle exec rake beaker:centos-7-x64` seems to fail because it's trying to write to `/etc/puppet/hiera.yaml` instead of `/etc/puppetlabs/puppet/hiera.yaml`. I'm not sure where it's getting `default['puppetpath']` from, but I think the tests don't need this line anyway?
=> don't "touch" hiera.yaml in spec_helper_acceptance

lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb
Queue arguments and properties are now parsed by tabs instead of spaces.
=> Bug fix for when queue names include spaces

manifests/install/rabbitmqadmin.pp
It is an equivalent of curl_option='-k'.
=> Do not check cert when acquiring rabbitmqadmin with wget.

README.md, lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb, lib/puppet/type/rabbitmq_binding.rb, spec/acceptance/queue_spec.rb, spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/type/rabbitmq_binding_spec.rb
Updated: proposing this as an option instead of #375 
This PR lets you specify legacy style resources (`source@destination@vhost`) and / or lets you specify `source`, `destination` (and, optionally, `routing_key` and `vhost`) as separate parameters, with a descriptive or arbitrary name.
There's still probably some room for improvement, but I've finally got this in shape where I think it could be merged.
=> Multiple routing keys for bindings using namevars

lib/puppet/provider/rabbitmq_policy/rabbitmqctl.rb, spec/acceptance/policy_spec.rb
This reworks #482, and keeps attribution, but adds the spec test that @DrOwl posted. cc: @eputnam @sspreitzer @devfaz
=> Fix regex double escaping of rabbitmqctl list_policies

spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_exchange/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_plugin/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_queue/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_user_permissions/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_vhost/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_binding_spec.rb, spec/unit/puppet/type/rabbitmq_exchange_spec.rb, spec/unit/puppet/type/rabbitmq_parameter_spec.rb, spec/unit/puppet/type/rabbitmq_plugin_spec.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb, spec/unit/puppet/type/rabbitmq_queue_spec.rb, spec/unit/puppet/type/rabbitmq_user_permissions_spec.rb, spec/unit/puppet/type/rabbitmq_user_spec.rb, spec/unit/puppet/type/rabbitmq_vhost_spec.rb
Switch to 'let(:foo)' syntax (resolves rubocop warnings)
=> Switch to 'let(:foo)' syntax (resolves rubocop warnings)

manifests/repo/rhel.pp, spec/classes/rabbitmq_spec.rb, spec/spec_helper_local.rb
Proposed fix for #573 -- this works around the issue where RHEL wants to hit 7Client / 7Server instead of 7 (which Packagecloud doesn't seem to have setup as valid names).
=> Switch $releasevar to ${::os[release][major]}

manifests/params.pp, metadata.json, spec/classes/rabbitmq_spec.rb, spec/spec_helper_local.rb
=> Add FreeBSD support

lib/puppet/type/rabbitmq_plugin.rb, lib/puppet/type/rabbitmq_vhost.rb
This also caused two Lint/Void rubocop violations which are now fixed.
=> Fix namevar parameter documentation in types

lib/facter/erl_ssl_path.rb, manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, spec/spec_helper_local.rb
As mentioned in the RabbitMQ documentation [1], this sets up the
necessary parameters through environment variables to use the relevant
-proto_dist value, and enable the ssl path (through the -pa option) if
necessary.
[1] https://www.rabbitmq.com/clustering-ssl.html
=> Enable configuring SSL for Erlang distribution

.fixtures.yml
Typo in .fixtures.yml breaking unit tests ( at least on a windows machine )
=> Typo in .fixtures.yml breaking unit tests

lib/facter/erl_ssl_path.rb, manifests/config.pp, manifests/init.pp, manifests/repo/apt.pp, manifests/repo/rhel.pp
This just fixes some linter warnings, plus 2 minor rubocop warnings I forgot to enforce for another recent PR.
=> update various small warnings

manifests/config.pp, manifests/init.pp, manifests/params.pp, manifests/repo/rhel.pp, spec/acceptance/class_spec.rb, spec/acceptance/clustering_spec.rb, spec/acceptance/delete_guest_user_spec.rb, spec/acceptance/parameter_spec.rb, spec/acceptance/policy_spec.rb, spec/acceptance/queue_spec.rb, spec/acceptance/rabbitmqadmin_spec.rb, spec/acceptance/server_spec.rb, spec/acceptance/user_spec.rb, spec/acceptance/vhost_spec.rb, spec/classes/rabbitmq_spec.rb, spec/spec_helper_acceptance.rb
This is failing one test currently
=> switch to structured facts for os* and rabbitmq_version

examples/erlang_deps.pp, examples/full.pp, examples/plugin.pp, examples/repo/apt.pp, examples/server.pp, examples/service.pp, examples/site.pp
This seems to make modulesync complain
=> update more lint warnings for relative classname inclusion in examples

spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_policy/rabbitmqctl_spec.rb
I think this is an improvement.
=> move these tests to a context block, and use 'let(:foo)' syntax

spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_parameter_spec.rb, spec/unit/puppet/type/rabbitmq_queue_spec.rb, spec/unit/puppet/type/rabbitmq_user_spec.rb
This should help reduce the # of multiple expectation warnings.
=> Remove redundant specs, rework others to avoid multiple expectation warnings

.fixtures.yml, manifests/install/rabbitmqadmin.pp, metadata.json, spec/classes/rabbitmq_spec.rb, spec/spec_helper_acceptance.rb, spec/spec_helper_local.rb
This PR switches the module to use the 'archive' module instead of 'staging'.
=> Convert to use 'archive' instead of 'staging' for rabbitmqadmin install

spec/unit/puppet/type/rabbitmq_policy_spec.rb
Would appreciate feedback on this one.
=> Eliminate more "multiple expectations" warnings and remove some redundant specs

spec/acceptance/parameter_spec.rb, spec/acceptance/policy_spec.rb, spec/acceptance/queue_spec.rb, spec/acceptance/user_spec.rb, spec/acceptance/vhost_spec.rb, spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/type/rabbitmq_user_permissions_spec.rb
Disable / ignore the remaining 'multiple expectations' warnings in acceptance tests and in 2 other specs until we can get good fixes in place for them.
=> Ignore remaining multiple expectations warnings

README.md
I linked to `.git/CONTRIBUTING` rather than `.github/CONTRIBUTING`, resulting in a broken link.
=> Fix typo (.git => .github) in README link

lib/facter/erl_ssl_path.rb, spec/unit/facter/util/fact_erl_ssl_path_spec.rb
(this is a re-submission of #606)
Hi there,
This small PR fixes two small issues with the `erl_ssl_path` fact.
The first is pretty straightforward: avoid the `.gsub` call if we didn't actually get any data to mangle.
The second is a bit less clear-cut: drop the use of `.with_env` while calling `erl`. Newer versions of facter (>=3) AFAIK stopped supporting it (compare [2.x docs](https://puppetlabs.github.io/facter/2.0.x/Facter/Util/Resolution.html) with [3.x docs](https://puppetlabs.github.io/facter/master/structfacter_1_1ruby_1_1resolution.html)) and it was unclear why we needed it in the first place. If I'm missing something and it *is* needed in some case, I'd be happy to find another workaround.
It also adds simple testing for `erl_ssl_path`.
Cheers
=> fix a couple of problems with erl_ssl_path fact

lib/facter/rabbitmq_nodename.rb, lib/facter/rabbitmq_version.rb, spec/unit/facter/util/fact_rabbitmq_nodename_spec.rb, spec/unit/facter/util/fact_rabbitmq_version_spec.rb
This updates to 'expect' style rspec syntax, and switch to `Facter::Util::Resolution` (vs `Execution`), thanks @dhollinger
=> Avoid error when rabbitmqctl is not present), update spec syntax (#614)

manifests/init.pp, spec/classes/rabbitmq_spec.rb
Update class ordering to follow current best practices.
This also removes some apparently redundant uses of `require => Class['rabbitmq::install']`
=> Switch to 'contain' vs. anchor pattern, and use Class['foo'] vs Class['::foo']

README.md, lib/puppet/type/rabbitmq_binding.rb, lib/puppet/type/rabbitmq_erlang_cookie.rb, lib/puppet/type/rabbitmq_exchange.rb, lib/puppet/type/rabbitmq_parameter.rb, lib/puppet/type/rabbitmq_plugin.rb, lib/puppet/type/rabbitmq_policy.rb, lib/puppet/type/rabbitmq_queue.rb, lib/puppet/type/rabbitmq_user.rb, lib/puppet/type/rabbitmq_user_permissions.rb, lib/puppet/type/rabbitmq_vhost.rb, manifests/init.pp, manifests/params.pp
This is a first pass at moving docs to puppet-strings, starting with params and examples. Only bad thing is that we might want to move some of the params that aren't os specific back to init.pp at some point, so that it's easier to see default params in the docs.
=> Move examples and params to puppet strings style docs

manifests/init.pp, manifests/install/rabbitmqadmin.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb
This is needed for Ubuntu 16.04+ where only Python 3 is installed by default.
This could cause issues in some cases where people have defined the Python package elsewhere, I'm open to suggestions on how to do this more sanely, though really hoping to avoid an additional parameter.
If RabbitMQ distributed it in the package, the dependency could be handled more cleanly.
=> BREAKING: Ensure python package (adds manage_python option)

.sync.yml, .travis.yml, manifests/config.pp, metadata.json, spec/classes/rabbitmq_spec.rb
I think we can avoid making bigger changes to tests or systemd for now by just hitting `/bin/systemctl` on both Ubuntu and CentOS systems.
This will still depend on #623 (or the equivalent) for acceptance tests to pass in Travis, however, unless we explicitly force the python package in the Docker image.
=> Add official support for Ubuntu 16.04

spec/classes/rabbitmq_spec.rb
This should improve the test coverage for #623
=> Fix test cases for #623 (manage_python)

lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb
From #566, it seems as if the command in `/sbin` should be preferred, at least with modern RabbitMQ versions. Not sure if we need to get too smart about it, or how far back we need to support in terms of versions... presumably it would be possible to have it fall back to the second path, but not sure if that's overkill.
=> Switch back to using rabbitmq-plugins from system path (#566)

lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb, lib/puppet/type/rabbitmq_user.rb, spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_user_spec.rb
This breaks out the fix for #147 (though it's also handled in #598 with the alternate implementation of rabbitmq_user type / provider)
=> Resolve issue with "puppet resource rabbitmq_user" failing (#147)

lib/facter/erl_ssl_path.rb
I think switching it to a symbol is preferred.
=> Switch string to symbol for erl_ssl_path fact definition

CHANGELOG.md, metadata.json
This release includes some breaking(ish) changes, so we're going to do a major bump.
=> 7.0.0 release

metadata.json
switch lowest supported version back to 4.7.1
=> Lower required Puppet version from 4.8.0 to 4.7.1

manifests/init.pp, manifests/params.pp, manifests/repo/apt.pp, manifests/repo/rhel.pp, spec/classes/rabbitmq_spec.rb
Could use some feedback on this, especially in terms of whether the packagecloud repo key itself needs to be configurable, and whether using the mit pgp server is the best way to get the key (it seems safer than grabbing it from the packagecloud site directly).
I couldn't find an easy way around doing variable interpolation in the repo source in the spec tests, but open to suggestions / examples of how to do it better.
=> Rework apt to use packagecloud repos as well (#640)

lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb, lib/puppet/type/rabbitmq_user.rb, spec/acceptance/user_spec.rb, spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb
This is an attempt to rework #460 by @mpolenchuk (keeping original attribution).
Could use careful review, rebasing was pretty hairy, and not sure I got everything.
As of now, failing at least one test.
=> Refactor rabbitmq_user provider (mpolenchuk)

manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
This change makes ldap_user_dn_pattern optional.
Per the [docs](https://www.rabbitmq.com/ldap.html):
> If you set both dn_lookup_attribute and user_dn_pattern then the approaches are combined: the plugin fills out the template and then searches for the DN
Sometimes this behaviour isn't wanted and user_dn_pattern needs to be omitted.
=> Make ldap_user_dn_pattern optional

manifests/init.pp, manifests/params.pp, manifests/repo/apt.pp, spec/classes/rabbitmq_spec.rb
I think this also gets rid of the remaining `validate_` calls.
for `package_apt_pin`, I have:
`Optional[Variant[Numeric, String]] $package_apt_pin`, which is a little looser than what was there before, but seems consistent to what the apt module itself allows? I could require it to be numeric instead if we think that's better.
for `file_limit`, I have:
`Variant[Integer[-1,], Enum['unlimited', 'infinity']] $file_limit = $rabbitmq::params::file_limit,`
which I think approximates the old behavior, except requiring integers to be numeric rather than strings.
Open to suggestions on how (maybe just do custom types instead, in a separate file) to avoid having this push the spacing so far out in the class params.
=> BREAKING: Remove deprecated manage_repos parameter and disallow strings for integer parameters

lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb, lib/puppet/type/rabbitmq_binding.rb, spec/acceptance/queue_spec.rb, spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/type/rabbitmq_binding_spec.rb
This should fix #650. It also
- Reformats the binding provider spec tests to be a little easier to read
- Adds a basic test for `puppet resource rabbitmq_binding` in the acceptance tests. This way, we should notice if a problem comes up with this command in the future.
Since we got feedback on how to test this in the type rather than in the create method in the provider, I can try to submit a separate PR to fix this for the rabbitmq_user resource.
Some of the other providers don't have instances implemented, so won't work with `puppet resource`; this is a separate issue, though refactoring them would be a good project for someone with the time on their hands 😉
=> Fix 'puppet resource rabbitmq_binding' and add tests (#650)

README.md
=> use correct datatype for port param in README.md

manifests/init.pp, manifests/repo/rhel.pp
They parameter $package_gpg_key is only defined if it is a RHEL box. The
setup fails on every other system, because it was a required param. This
PR changes the main class to also accept undef, and updates the RHEL
specific repo class to only accept Strings
=> use correct datatype for $package_gpg_key

manifests/init.pp, manifests/install/rabbitmqadmin.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb
=> allow installation of rabbitmqadmin via package

manifests/init.pp, manifests/params.pp
in case the package has subpackages (like it does for the SUSE family
OSes)
=> add ability to have array as package name

manifests/install/rabbitmqadmin.pp
due to the dependency of the module from `puppet-archive`, there is no need to make the require. Is also really hard to debug, because the puppet exception doesn't clearly refers to the module requirement (duplicate declaration)
=> Remove `archive require` in rabbitmqadmin class

lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_erlang_cookie/ruby.rb, lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb, lib/puppet/provider/rabbitmq_policy/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_user_permissions/rabbitmqctl.rb
It is sometimes useful to be able to noop (or change) a provider in
certain situations [1] (Think running a temporary container with puppet
tags to create proper config files). Currently, using defaultfor makes
overriding the current provider rabbitmqctl a very hard thing to do.
Let's switch to using the confine mechanism to make sure the provider
runs only on posix OSes while still allowing an operator to override it.
[1] https://github.com/openstack/puppet-tripleo/blob/master/lib/puppet/parser/functions/noop_resource.rb
=> Do not use defaultfor to choose the only existing provider

manifests/init.pp, manifests/install/rabbitmqadmin.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb
This adds a new parameter `archive_options`, allowing an array of options which can be passed to the archive module for downloading rabbitmqadmin.
=> Add archive_options parameter for Archive download of rabbitmqadmin

.msync.yml, .travis.yml, Gemfile, manifests/config.pp, spec/acceptance/nodesets/fedora-26-x64.yml, spec/acceptance/nodesets/fedora-27-x64.yml, spec/classes/rabbitmq_spec.rb
=> Fixes for Archlinux and modulesync 1.8

manifests/init.pp, manifests/install.pp, manifests/repo/apt.pp, manifests/repo/rhel.pp, metadata.json, spec/classes/rabbitmq_spec.rb
This fixes an issue with the package resource accepting an array for `$title`, but not for the name parameter. I'm not sure why it was originally coded this way, but it seems to work with one more minor adjustment to the Arch tests (now that #685 is merged).
It adds support in metadata.json for SLES 11 (only) to test the additional package we expect there. I didn't add support for SLES 12 or openSUSE because I'm not 100% sure about the versioning, and >=12 has systemd, so there are some additional adjustments needed there that should probably be done by someone who can do more testing and who knows the versioning situation (for example, we may not want to just do systemd based on >=12 because of the weird numbering w/ openSUSE).
Additionally, it slightly simplifies the resource …
=> Install package via title, not name (#684)

manifests/params.pp
This attempts to work around issues experienced related to LC_ALL not being set in a fairly conservative way, by setting it explicitly in the `$environment_variables` hash.
Not sure if we should do a merge with user-passed in ones, or if there is a better way to format this, but seems like it could help avoid issues? I will see if this runs against Ubuntu 16 in acceptance tests, but would be great if someone could test that this works properly and doesn't cause unintended consequences.
I guess that the main way it could cause issues would be if someone had a resource with 8 bit characters in the name, and didn't explicitly set another env? We could default to UTF-8, but C seems more conservative.
=> Explicitly set LC_ALL to C (#689)

CHANGELOG.md, metadata.json
Release better bugfix for error with some newer versions of RabbitMQ when locale is not UTF-8.
=> Release 8.2.2

manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
The aim of this pull request is to give the possibility to allow remote connections with the guest user, of course this is not the default configuration, because it implies some security risks 
Fixes #698
=> Add loopback_users parameter (adds ability to allow guest user to login remotely)

lib/facter/rabbitmq_version.rb, spec/unit/facter/util/fact_rabbitmq_version_spec.rb
If the `rabbitmq_version` string returned from `rabbitmqadmin --version` contains invalid characters it throws an error because the array is nil. This will make a empty array out of it so it won't throw an error in that case.
Fixes #704
=> Ensure version fact does not throw an error for invalid match

templates/inetrc.erb
Linting validation fails on this file.
=> Updated comment symbol on inetrc.erb

lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb
For instance, if you set `durable = false` it would not define `durable` which would default to `true`.
=> Some boolean properties were being ignored when `false`.

metadata.json
Require puppet-archive >=2.0.0 so that `download_options` should be present.
Fixes #706
=> Set lower limit for puppet-archive to 2.0.0

README.md, manifests/init.pp
This adds a note in the README, and adds missing Puppet strings docs for `config_ranch` in the main manifest.
See #618 and #621 for more details.
Fixes #719
=> Add docs for config_ranch parameter

manifests/config.pp, spec/classes/rabbitmq_spec.rb
As pointed out in [this comment](
https://github.com/voxpupuli/puppet-rabbitmq/pull/683#discussion_r216639952), and as I'm finding out in practice now, the override/limits file can be created for the wrong systemd unit name, `rabbitmq.service` instead of `rabbitmq-server.service`.
This is a bug in the 8.3.0 release since #715 which was based on my (broken) code in #683.
I haven't created an issue. Can if needed.
=> Fix service name in systemd service limits config

manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb
Make the restart optional since it is dangerous to do an uncontrolled rolling restart. We lost many messages this way. 
It has been many years since I have written any puppet code so I don't have high confidence that I did this entirely correct. It is based off of how the kafka module prevents rolling restarts https://github.com/voxpupuli/puppet-kafka/search?q=service_restart&unscoped_q=service_restart
Fixes #727
=> Add service_restart option to prevent automatic service reload

.fixtures.yml, .github/CONTRIBUTING.md, .msync.yml, .sync.yml, .travis.yml, Gemfile, manifests/repo/apt.pp, spec/classes/rabbitmq_spec.rb, spec/default_facts.yml, spec/spec_helper.rb, spec/unit/facter/util/fact_erl_ssl_path_spec.rb, spec/unit/facter/util/fact_rabbitmq_nodename_spec.rb, spec/unit/facter/util/fact_rabbitmq_version_spec.rb
=> modulesync 2.2.0 and allow puppet 6.x

lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_cli.rb, lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb, lib/puppet/provider/rabbitmq_policy/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_user_permissions/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_vhost/rabbitmqctl.rb, lib/puppet/type/rabbitmq_binding.rb, spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_cli_spec.rb, spec/unit/puppet/provider/rabbitmq_exchange/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_policy/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_queue/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_user_permissions/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_vhost/rabbitmqctl_spec.rb
This is an alternative attempt at fixing `rabbitmqctl list_{x}` commands with RabbitMQ 3.7.9+. #751 was also an attempt. This PR takes a different approach by adding a class method in the "parent" provider class for all the providers. This method provides a consistent way to run `rabbitmqctl list_` operations in all provider classes.
This PR also cleans up the process of finding RabbitMQ CLI binaries: all providers now share the same command methods. It also adds caching to the RabbitMQ version value.
Fixes #740
=> RabbitMQ 3.7.9+ list compatibility and provider cleanup

.travis.yml, metadata.json, spec/spec_helper_acceptance.rb
This PR adds official (metadata.json + Tests) for Ubuntu 18.04.
Fixes #757.
=> Officially support Ubuntu 18.04

.travis.yml, CHANGELOG.md, lib/puppet/provider/rabbitmq_cli.rb, metadata.json
=> Release 8.5.0

lib/puppet/provider/rabbitmq_cli.rb, lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb, lib/puppet/type/rabbitmq_plugin.rb, spec/unit/puppet/provider/rabbitmq_plugin/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_plugin_spec.rb
Hello Pupuli!
In RabbitMQ we could enable a plugin offline or online.
Some plugins should be enabled offline.
See https://www.rabbitmq.com/plugins.html#ways-to-enable-plugins
man rabbitmq-plugins
=> Allow offline and online mode for plugins

lib/facter/rabbitmq_plugins_dirs.rb, spec/unit/facter/util/fact_rabbitmq_plugins_dirs_spec.rb
If you want to add third party plugins with puppet you need to know
where the plugins folder is located.
This can differ depending on rabbitmq version or OS.
=> Add a custom fact for rabbitmq's plugins folder.

manifests/config.pp, manifests/init.pp, manifests/install/rabbitmqadmin.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/enabled_plugins.erb, templates/rabbitmq.config.erb
Support configuring plugins using enabled_plugins file
Adds optional support to configure rabbitmq plugins by
writing configuration file (/etc/rabbitmq/enabled_plugins).
New parameter $use_config_file_for_plugins (boolean, default:
false) Can be used to enable this feature. When enabled it
replaces the use of the rabbitmqplugins provider to enable
plugins.
Fixes #775
=> Add support for enabled plugins config using enabled_plugins file

lib/puppet/type/rabbitmq_parameter.rb, spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_parameter_spec.rb
Array (lists) are allowed values to use with rabbitmqctl.
For example: src-uri when setting up a shovel.
@wyardley could you re-review this, had to create a new pr since I have left the vrtdev organisation since the previous one :)
=> Allow Array values in rabbitmq_parameter

lib/facter/rabbitmq_plugins_dirs.rb
Before trying to access the contents of a regexp match, see if the
match was successful. On machines without rabbitmqctl this match will
return nil. If we try to index the nil with `[1]`, it will crash.
Fixes #783
=> Don't crash on rabbitmq_plugins_dirs fact if rabbitmqctl is not present

manifests/init.pp
This is a very simple suggestion on how to improve the documentation. It may be natural to assume that `ensure_repos => True` should fix erlang dependencies, a minor comment that it doesn't could be sufficient to avoid frustrations.
This pull request does not fix any issues, but does improve the situation wrg of #788.
=> Slightly improved documentation of the ensure_repos parameter.

manifests/params.pp
this fixes a configuration error on the FreeBSD platform
where is the 3rd-party software configuration placed
has a prefix /usr/local.
Tested on: FreeBSD 12.0-RELEASE, FreeBSD-13-HEAD
=> make config path distribution-dependent

manifests/repo/apt.pp
The resource ```Exec['apt_update']``` is triggered by default since ```puppetlabs/apt 2.4.0```:
* https://github.com/puppetlabs/puppetlabs-apt/blob/master/CHANGELOG.md#supported-release-240
* https://github.com/puppetlabs/puppetlabs-apt/commit/0475e50be8e4994e4c1c22ce103e903f52c2c599
Fixes #780
=> Remove ordering of classes

manifests/install/rabbitmqadmin.pp
With change f223f66894e5e948bcd2cf05d7beaa911605b3ff (Convert to use
'archive' instead of 'staging' for rabbitmqadmin install) the
`$curl_prefix` variable became unused:
```
$ grep -ir curl_prefix
manifests/install/rabbitmqadmin.pp:      $curl_prefix = ''
manifests/install/rabbitmqadmin.pp:      $curl_prefix  = "--noproxy ${management_ip_address} -g -6"
manifests/install/rabbitmqadmin.pp:      $curl_prefix  = "--noproxy ${management_ip_address}"
```
Let's just remove them. Users have means to specify options
to the puppet-archive provider anyways.
Removes confusing unused variables that led to #799 being opened (not using the Fixes keyword explicitely as it would be incorrect)
=> Remove unused curl_prefix variable

manifests/config.pp, manifests/init.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb, templates/rabbitmqadmin.conf.erb
=> Add optional variables for SSL management-console

lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb, lib/puppet/type/rabbitmq_parameter.rb, spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb
I refactored the rabbitmq_parameter provider because I need an 'instances' class method to use [puppet-purge](https://github.com/crayfishx/puppet-purge) on undeclared shovels.
=> Refactor rabbitmq_parameter provider

REFERENCE.md
Replace the URL from the archived repo to the current repo of `rabbitmq-autocluster`.
If it is possible for someone to change: The repository description of this repo which is currently "RabbitMQ Puppet Module http://forge.puppetlabs.com/puppetlab…" links to the deprecated forge puppet plugin `https://forge.puppet.com/puppetlabs/rabbitmq` and should link to `https://forge.puppet.com/puppet/rabbitmq`.
None
=> Update link to rabbitmq-autocluster

lib/puppet/provider/rabbitmq_cli.rb
Where the output from `rabbitmqctl -q status` isn't printed as an Erlang
property list.
Without this change, you get a crash with error:
> Failed to apply catalog: undefined method `scan' for nil:NilClass
=> Extend version regex for RabbitMQ 3.8

REFERENCE.md, manifests/init.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
Currently, this module only supports the old Erlang style, but RabbitMQ post-3.7.9 (rabbitmq/rabbitmq-server#1712) supports the OpenSSL style.
This change allows the rabbitmq.config file to determine which style is being used, and apply that when defining SSL cipher suites.
n/a
=> Update the ssl_ciphers parameter to support the OpenSSL style

.github/CONTRIBUTING.md, .travis.yml, CHANGELOG.md, Dockerfile, Gemfile, Rakefile, metadata.json, spec/spec_helper.rb
BREAKING CHANGE: Drop Ubuntu 14.04 support (#818)
- Extend version regex for RabbitMQ 3.8 (#814)
- Clean up acceptance spec helper (#815)
Fixes #817
=> Release 10.0.0 + modulesync

data/family/FreeBSD.yaml
When provisioning on FreeBSD the following error was occurring:
```
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /usr/loca/etc/rabbitmq/rabbitmq-env.conf20200114-5149-136fx0a.lock (file: /usr/local/etc/puppet/code/environments/feature_starling_vagrant/modules/rabbitmq/manifests/config.pp, line: 170)
Error: Could not set 'file' on ensure: No such file or directory @ dir_s_mkdir - /usr/loca/etc/rabbitmq/rabbitmq-env.conf20200114-5149-136fx0a.lock (file: /usr/local/etc/puppet/code/environments/feature_starling_vagrant/modules/rabbitmq/manifests/config.pp, line: 170)
Wrapped exception:
No such file or directory @ dir_s_mkdir - /usr/loca/etc/rabbitmq/rabbitmq-env.conf20200114-5149-136fx0a.lock
Error: …
```
=> Fix env_config_path on FreeBSD

manifests/config.pp, spec/acceptance/class_spec.rb, spec/classes/rabbitmq_spec.rb
* Set owner of config directories to rabbitmq user rather than root
* Set group of config directories explicitly to rabbitmq, and set setgid bit
* Set more restrictive permissions on the SSL directory
* Update expectations, and test file permissions in acceptance tests
This is a narrower version of #796 (@dhoppe)
This does have some security implications, since when the file is owned by root, if the application is compromised, the rabbitmq user still may not be able to modify configuration files; with these changes, it would.
I _believe_ that changing the ownership this way should be safe even on older RabbitMQ versions. However, would appreciate some eyes and / or actual testing of this, as I'm not in a good position to do extensive validations beyond the acceptance tests.
Fixes #703 …
=> [fix] ownership and permissions on conf files

manifests/config.pp, spec/classes/rabbitmq_spec.rb
Instead, use RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
Quoted from https://www.rabbitmq.com/configure.html#supported-environment-variables:
"
RABBITMQ_SERVER_ERL_ARGS - Standard parameters for the erl command
used when invoking the RabbitMQ Server. This should be overridden for
debugging purposes only. Overriding this variable replaces the default
value.
"
The default value of RABBITMQ_SERVER_ERL_ARGS on *nix is:
+P 1048576 +t 5000000 +stbt db +zdbbl 128000
So currently, if ipv6/tls is enabled, and the caller does not provide
its own default value of RABBITMQ_SERVER_ERL_ARGS, it will end up
overwriting those server defaults.
=> Don't use RABBITMQ_SERVER_ERL_ARGS

lib/puppet/type/rabbitmq_erlang_cookie.rb
Override the is_to_s and should_to_s
methods in the puppet property to make
sure it's not shown in outputs.
Closes: #837
=> Hide erlang cookie content

lib/puppet/type/rabbitmq_user.rb
Override the is_to_s and should_to_s
methods in the puppet property to make
sure it's not shown in outputs.
Closes: #839
=> Hide user password

lib/facter/rabbitmq_nodename.rb
Currently when facter checks for rabbitmq_nodename and rabbitmq
is not available due to a number of reasons. We get the following
facter error displayed:
Error: Facter: error while resolving custom fact "rabbitmq_nodename": undefined method `[]' for nil:NilClass
Since facter errors are non fatal anyway let's be a little friendlier.
Before this change:
$ puppet apply foo.pp
Error: Facter: error while resolving custom fact "rabbitmq_nodename": undefined method `[]' for nil:NilClass
Notice: Compiled catalog for messaging-0.redhat.local in environment production in 0.02 seconds
Notice: foo
Notice: /Stage[main]/Main/Notify[foo]/message: defined 'message' as 'foo'
After this change:
$ puppet apply foo.pp
Notice: Compiled catalog for messaging-0.redhat.local in environment production in 0.02 …
=> Remove facter rabbitmq_nodename error message

lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb
Escape double quotes during password comparison to fix bash unterminated string error
Fixes #850
=> Escape double quotes in password during comparison

CHANGELOG.md, metadata.json
Release 10.1.1
Changes:
- Escape double quotes in password during comparison (@jplindquist; #851)
- Remove facter rabbitmq_nodename error message (@mbaldessari; #849)
Not sure that #849 is really a bug or enhancement, but open to suggestions there.
=> [chore] release 10.1.1

manifests/config.pp, metadata.json, spec/classes/rabbitmq_spec.rb
It makes sure it's idempotent on RHEL based, needs an increase in systemd dependency to a minimum
versions of 2.10.0 to include the changes there.
Fixes: #836
=> Ignore SELinux defaults for systemd on RHEL based

manifests/init.pp
Hi,
I would like to propose this little change, as to what I was able to find out is not a valid option, and i'm not sure if it ever was.
The `disk` option was added in module version `5.0.0 (2014-12-22)`
See commit: https://github.com/voxpupuli/puppet-rabbitmq/commit/6c67f33d08f68e2cda898d0161f5820cd9f32c0e
and Puppetlabs ticket: https://tickets.puppetlabs.com/browse/MODULES-1186
The part on the clustering page referenced there is probably this:
https://www.rabbitmq.com/clustering.html#cluster-node-types
```
A node can be a disk node or a RAM node. (Note: disk and disc are used interchangeably).
RAM nodes store internal database tables in RAM only. This does not include messages, 
message store indices, queue indices and other node state.
```
Though it doesn't mention that the …
=> remove invalid cluster_node_type 'disk'

manifests/init.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
The RabbitMQ LDAP plug-in supports multiple servers being listed in the the "servers" field, but the puppet module currently only accepts a single String value.
My simple pull request allows an array of servers to be passed, which is then correctly formatted in the rabbitmq.confg template. I additionally attempt to detect an array that has already been flattened to a string, as happens if you configure the ldap_servers variable from hiera by way of sourcing an array variable that is already defined else where in puppet (rabbitmq::ldap_server: "%{ldap::servers}").
Tested and working with a string, an array, and a array flattened to a string.
=> Add support for multiple LDAP servers

lib/puppet/type/rabbitmq_parameter.rb, spec/unit/puppet/type/rabbitmq_parameter_spec.rb
Add a new parameter `autoconvert` for `rabbitmq_parameter` to allow users to disable auto type conversion from numeric strings to integers if needed.
We have several `x-content-hash` exchanges which use a numeric string as the routing key. Due to the `munge_value` [implementation](https://github.com/voxpupuli/puppet-rabbitmq/blob/2bcfb0e/lib/puppet/type/rabbitmq_parameter.rb#L82), the routing key would be converted to an integer. 
As a result, a valid payload to create a shovel as below
```json
{
"component": "shovel",
"vhost": "foo",
"name": "test",
"value": {
"src-uri": "amqps://user:[redacted]@rabbit.service.consul:5671/foo",
"src-exchange-key": "5",
"dest-uri": "amqps://user:[redacted]@rabbit.service.consul:5671/bar",
"dest-exchange-key": "5",
"ack-mode": "on-confirm",
"src-protocol": …
```
=> Add new parameter autoconvert for rabbitmq_parameter

lib/puppet/type/rabbitmq_parameter.rb, spec/unit/puppet/type/rabbitmq_parameter_spec.rb
Make sure `:autoconvert` is set before `:value` for `rabbitmq_parameter` since `:value` depends on `:autoconvert`.
This was done by overriding `set_parameters` for the type. It's hacky but there doesn't seem to be a better way to put put a parameter before a property since puppet lets `properties` take precedence over `parameters` -  https://github.com/puppetlabs/puppet/blob/7ef0811/lib/puppet/type.rb#L118-L124 . 
Note: my first attempt was to change `:autoconvert` to a property but that doesn't really fit. Because we don't store its value anywhere, having `:autoconvert` as a property will lead puppet to believe that there is always a change to the `:autoconvert`
```
Notice: /Stage[main]/Main/Rabbitmq_parameter[documentumFed@fedhost]/autoconvert: defined 'autoconvert' as 'true'
```
My …
=> Ensure :autoconvert is initialized before :value for rabbitmq_parameter

CHANGELOG.md, REFERENCE.md, metadata.json
Release 10.3.0:
* Add new parameter autoconvert for rabbitmq_parameter (@joec4i) (#865)
* Ensure :autoconvert is initialized before :value for rabbitmq_parameter (@joec4i) (#867)
* modulesync 3.1.0 (@bastelfreak) (#864)
* modulesync 4.0.0 (@bastelfreak) (#866)
=> Release 10.3.0

data/common.yaml, manifests/config.pp, manifests/init.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
Add support for SSL CRL (Certificate Revocation List) check options.
This option is not documented in official documentation but RabbitMQ supports these options because they are implemented in underlying [OTP SSL module](https://erlang.org/doc/man/ssl.html#type-crl_cache_opts).
There are 3 main use cases:
* Enable CRL check in `best_effort` mode (if certificate revocation status cannot be determined it will be accepted as valid) and without any cache
In this case, result configuration should look like this:
```
[
{rabbit, [
{ssl_listeners, [5671]},
{ssl_options, [{cacertfile,"/path/to/testca/cacert.pem"},
{certfile,"/path/to/server/cert.pem"},
{keyfile,"/path/to/server/key.pem"},
{verify,verify_peer},
{fail_if_no_peer_cert,false}]},
{crl_check, best_effort}
]}
].
```
* Enable CRL check in …
=> Add optional variables to support SSL CRL check configuration

Gemfile, spec/classes/rabbitmq_spec.rb, spec/spec_helper.rb, spec/spec_helper_local.rb
This uses the add_mocked_facts! from voxpupuli-test 2.2.0 rather than a local override.
A result of what https://github.com/voxpupuli/modulesync_config/pull/693 would do.
=> Use mocked facts in tests

lib/puppet/provider/rabbitmq_cli.rb
with the previous code there were scenarios where version on line 46 was empty and the following if did not work as expected.
=> make sure the rabbitmq_version method actually returns the version.

manifests/config.pp, manifests/init.pp, spec/classes/rabbitmq_spec.rb, templates/default.erb
Add support for OOM score in init script and systemd limits.
Default value is 0, acceptable values range from -1000 to +1000.
Documentation : Chapter 3.1 of https://www.kernel.org/doc/Documentation/filesystems/proc.txt
=> Add support for oom_score_adj

REFERENCE.md, data/common.yaml, examples/cluster/join_cluster_and_change_name.pp, lib/facter/rabbitmq_clustername.rb, lib/puppet/provider/rabbitmq_cluster/rabbitmqctl.rb, lib/puppet/type/rabbitmq_cluster.rb, manifests/init.pp, spec/acceptance/clustering_spec.rb, spec/unit/facter/util/fact_rabbitmq_clustername_spec.rb, spec/unit/puppet/provider/rabbitmq_cluster/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_cluster_spec.rb
This PR add the clustering management
- added clustername fact and spec tests for it
- added rabbitmq_cluster type and provider with tests
- rework of PR #736 
Fixes #792
Closes #736
=> Add auto cluster configuration support

manifests/service.pp, metadata.json
Remove `systemd::systemctl::daemon_reload`
Fails with puppet-systemd >= 3.0.0
See https://github.com/camptocamp/puppet-systemd/compare/2.12.0...3.0.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R224-R229
`systemd::systemctl::daemon_reload` was removed.
@ekohl
=> Compatibility with camptocamp/systemd 3.x

CHANGELOG.md, REFERENCE.md, metadata.json
- Add support for oom_score_adj (#877)
- CLI Environment Fixes (#876)
- make sure the rabbitmq_version method actually returns the version (#874)
- Use mocked facts in tests (#873)
- Enable Puppet 7 support (#881)
- Add auto cluster configuration support (#883)
- Compatibility with camptocamp/systemd 3.x (#886)
- puppetlabs/apt: Allow 8.x (#884)
- puppet/archive: Allow 5.x (#884)
- puppetlabs/stdlib: allow 7.x (#884)
=> Release 11.1.0

manifests/init.pp
Since RabbitMQ version 3.7.0, log level configuration has changed. Key "log_levels" has been replaced by categories.
> Log Message Categories
> RabbitMQ has several categories of messages, which can be logged with different levels or to different files.
>
> The categories replace the rabbit.log_levels configuration setting in versions earlier than 3.7.0.
Fixes #894 'Reference for log_levels does not apply'
=> Adjust docu for RabbitMQ log level #894

manifests/init.pp, manifests/install/rabbitmqadmin.pp
Add removal of rabbitmqadmin script and trigger refresh upon package upgrade or downgrade
Fixes #804
=> Fix Bug #804 'rabbitmqadmin will not be upgraded'

data/family/FreeBSD.yaml
Current python version for FreeBSD: 3.8
link: https://cgit.freebsd.org/ports/tree/Mk/bsd.default-versions.mk?h=2022Q1#n113
=> change default python version for FreeBSD: 3.8

data/common.yaml, data/family/RedHat.yaml, manifests/init.pp, manifests/repo/rhel.pp
We have notice some errors coming up with this module and it seems as so packagecloud has change the way they want their repos set up. We have had to update other repos as well.
Package cloud documentation:
https://packagecloud.io/rabbitmq/rabbitmq-server/install#bash-rpm
https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/config_file.repo?os=rhel&dist=8&source=script
Error:
```
Notice: /Stage[main]/Rabbitmq::Repo::Rhel/Exec[rpm --import https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey]/returns: executed successfully
Error: Execution of '/usr/bin/dnf -d 0 -e 1 -y install rabbitmq-server' returned 1: Importing GPG key 0xDF309A0B:
Userid     : "https://packagecloud.io/rabbitmq/erlang (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
Fingerprint: …
```
=> Fixing Yum repo

data/family/Archlinux.yaml, spec/classes/rabbitmq_spec.rb
Update Python package name to python instead of python2, and use file install vs. package install by default
Partially rolls back #654, though continues to allow the user to set the package via `$rabbitmqadmin_package`
This gets acceptance tests (partially) working again for Arch
=> Use default install method on Archlinux

lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb, spec/unit/puppet/provider/rabbitmq_plugin/rabbitmqctl_spec.rb
The rabbitmq_plugin resource use the "rabbitmq-plugins"-command when
enumerating enabled plugins.  Starting with rabbitmq 3.10, this command
will output a informational message:
'Listing plugins with pattern ".*" ...' which can be hidden with the -s
or -q parameter.  However, this approach will break rabbitmq_plugin on
older versions of RabbitMQ.
This patch implements a workaround that simply ignores the outputted line
if it exists.
Fixes: #909
=> Make rabbitmq_plugin resource functional on RabbitMQ 3.10.x

manifests/config.pp
This resolves the current error when the sintax test runs:
```
$ bundle exec rake lint
manifests/config.pp:131:manifest_whitespace_opening_brace_before:ERROR:there should be a single space before an opening brace
```
=> Minor fix to resolve a linting check

manifests/config.pp, manifests/init.pp, spec/classes/rabbitmq_spec.rb, templates/enabled_plugins.erb
This PR enables usage of a custom list of plugins when using a plugins config file, as reported on #916
=> Enable usage of custom list of plugins when using static config file

manifests/init.pp
Noticed these when reading the docs.
N/A.
=> docs: fix minor grammar & typo

manifests/install/rabbitmqadmin.pp
This fixes inconsistent logic to determine management ip address if the rabbitmq::management_ip_address parameter is not set, and makes sure all logic tries to look up the rabbitmq::node_ip_address parameter.
N/A
=> Fix detection of management_ip_address for rabbitmqadmin

spec/classes/rabbitmq_spec.rb
#927 removed Puppet 6 support, so we should be safely able to remove these testing workarounds
=> Remove testing workarounds from Puppet < 6

lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb, metadata.json, spec/acceptance/clustering_spec.rb, spec/unit/puppet/provider/rabbitmq_plugin/rabbitmqctl_spec.rb
- Deprecate Debian 9 and Ubuntu 16.04
- Add support for Debian 10
- Minor test updates (remove `RABBITMQ_USE_LONGNAME` in clustering acceptance tests)
- Fix rabbitmq_plugin to correctly detect implicitly enabled plugins (Cherry-picked from #844)
Closes #844
Fixes #930
Fixes #887
=> Remove support for Debian 9 and Ubuntu 16.04; Add Debian 10 support

manifests/install/rabbitmqadmin.pp, metadata.json
- Increase minimum stdlib to 4.25.0
- Remove `Stdlib::Compat` for `Stdlib::IP::Address::V6::Nosubnet`
https://forge.puppet.com/modules/puppetlabs/stdlib/readme
Resolves test failures with latest stdlib
=> Remove deprecated `Stdlib::Compat`

metadata.json, spec/classes/rabbitmq_spec.rb
Update tests and metadata to support FreeBSD 12 and 13 This also helps us unit test the (otherwise untested) conditionals related to systems without systemd
We may still need to tweak the current python package name, but this is a start
Per @bastelfreak's suggestion, use `os_facts` to avoid confusion with 
`:facts`
=> Support FreeBSD 12 and 13

metadata.json, spec/classes/rabbitmq_spec.rb
- Drop official metadata.json support for Archlinux until the acceptance tests can be fixed
- Replace legacy :osfamily in spec tests
=> BREAKING: Drop official Archlinux support

lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb, spec/acceptance/parameter_spec.rb
`resource[:component_name]` is set on creation (`ensure => present`) and deletion (`ensure => absent`) of the rabbitmq_parameter type but it is not set when it's removed from puppet-purge.
On the other hand,  `component_name` is set to absent on creation, is set on deletion and on purge.
```
resource[:component_name]          component_name
creation          shovel                           :absent
deletion          shovel                           shovel
purge              nil                             shovel
```
When deleting a parameter, replace `resource[:component_name']` with `resource[:component_name] || component_name`.
this bug was introduced by #833 (for #832)
=> fix purge rabbitmq_parameter

lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
Similiar to https://github.com/voxpupuli/puppet-rabbitmq/pull/628, the policy setting `initial-cluster-size` needs to be parsed into an integer before being passed to RMQ. 
Fixes this:
```
Error:
Validation failed
<<"3">> is not a valid cluster size
```
=> Treat `initial-cluster-size` option in policy as an integer

lib/puppet/provider/rabbitmq_policy/rabbitmqctl.rb, spec/unit/puppet/provider/rabbitmq_policy/rabbitmqctl_spec.rb
Related to https://github.com/voxpupuli/puppet-rabbitmq/pull/948 - this allowed us to add policies targeted at classic_queues, quorum_queues, and streams. However after the policy is created and they are read out again in subsequent puppet runs, we get the following failure:
```
Could not evaluate: cannot parse line from list_policies
```
This modification fixes this parsing issue and adds a test which covers this change and also covers test parsing a set of alternative policy settings which aren't currently tested for (different pattern/definitions containing integer values).
=> Bugfix: Fix parsing issue for queue policies targeted at quorum queues

REFERENCE.md, lib/puppet/provider/rabbitmq_vhost/rabbitmqctl.rb, lib/puppet/type/rabbitmq_vhost.rb, spec/unit/puppet/provider/rabbitmq_vhost/rabbitmqctl_spec.rb
Adding support for Vhost metadata - resolves https://github.com/voxpupuli/puppet-rabbitmq/issues/963
Allows for the following resource definition:
```
rabbitmq_vhost { 'myvhost':
ensure             => present,
description        => 'myvhost description',
tags               => ['tag1', 'tag2'],
default_queue_type => 'quorum',
}
```
Puppet run:
```
Notice: /Stage[main]/Test_rabbitmq::Server::Vhosts/Rabbitmq_vhost[test_no_desc_or_tags_or_queue_type-temp]/ensure: created
Notice: /Stage[main]/Test_rabbitmq::Server::Vhosts/Rabbitmq_vhost[test_tags_and_desc_stream_no_queue_type-temp]/ensure: created
Notice: /Stage[main]/Test_rabbitmq::Server::Vhosts/Rabbitmq_vhost[test_no_desc_or_tags_stream-temp]/ensure: created
Notice: /Stage[main]/Test_rabbitmq::Server::Vhosts/Rabbitmq_vhost[test_desc_no_tags_ …
```
=>  Add support for Vhost metadata 

lib/puppet/provider/rabbitmq_vhost/rabbitmqctl.rb
This fixes the error:
```
Error: Could not prefetch rabbitmq_vhost provider 'rabbitmqctl': Command rabbitmqctl is missing
```
The problem, and the workaround, are the same as that described in commit 8a3a27a0584666e71bf64b2eb49adf79133939c1, "add a workaround for running with --noop or --tags".
This is necessary because the original workaround is for `rabbitmqctl_list()`, whereas `rabbitmq_version()` calls `rabbitmqctl()` directly.
Other callers of `rabbitmq_version()` should not need this workaround, since they are not run in a state where rabbitmq itself is not yet installed.
Fixes #961
=> add a workaround for rabbitmq_vhost when running with --noop or --tags

.puppet-lint.rc, .sync.yml, REFERENCE.md, lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_cluster/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_erlang_cookie/ruby.rb, lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb, lib/puppet/provider/rabbitmq_policy/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_user/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_user_permissions/rabbitmqctl.rb, lib/puppet/provider/rabbitmq_vhost/rabbitmqctl.rb, lib/puppet/type/rabbitmq_binding.rb, lib/puppet/type/rabbitmq_cluster.rb, lib/puppet/type/rabbitmq_erlang_cookie.rb, lib/puppet/type/rabbitmq_exchange.rb, lib/puppet/type/rabbitmq_parameter.rb, lib/puppet/type/rabbitmq_plugin.rb, lib/puppet/type/rabbitmq_policy.rb, lib/puppet/type/rabbitmq_queue.rb, lib/puppet/type/rabbitmq_user.rb, lib/puppet/type/rabbitmq_user_permissions.rb, lib/puppet/type/rabbitmq_vhost.rb, manifests/init.pp, manifests/repo/apt.pp, manifests/repo/rhel.pp, manifests/service.pp
Might be backwards incompatible due to codebase hardening. Hardening occurs in:
- repo::apt
- repo::rhel
- service
All of those are either changing String to String[1] (disallowing empty Strings) or add a String datatype to variables already having a default String value
=> Harden codebase and add documentation stubs

lib/puppet/type/rabbitmq_parameter.rb, spec/unit/puppet/type/rabbitmq_parameter_spec.rb
This achieves almost the same, except that this version doesn't change the original value. If that's really desired, `transform_values!` can be used. It makes it clearer what's going on.
=> Use a more expressive method of rewriting values

.fixtures.yml, README.md, manifests/init.pp, spec/acceptance/class_spec.rb, spec/acceptance/clustering_spec.rb, spec/acceptance/delete_guest_user_spec.rb, spec/acceptance/parameter_spec.rb, spec/acceptance/policy_spec.rb, spec/acceptance/queue_spec.rb, spec/acceptance/rabbitmqadmin_spec.rb, spec/acceptance/user_spec.rb, spec/acceptance/vhost_spec.rb, spec/spec_helper_acceptance.rb
Historically we used the garethr/erlang module as soft dependency on CentOS 7. This also configured the EPEL7 repository. I always always a bit unsure where the actual rabbitmq packages come from. I assumed somehow from the erlang repo. My impression is that the erlan repo isn't used at all. rabbitmq packages where always pulled from EPEL7. The problem with the garethr/erlang is that it depends on the deprecated `stahnma/epel` (which is now puppet/epel) and uses topscope facts and
variables. The module doesn't work anymore with Puppet 8.
This PR replaces the unused garethr/erlang directly with the EPEL module.
=> CentOS7: default to EPEL7 as source

lib/puppet/provider/rabbitmq_cluster/rabbitmqctl.rb, metadata.json, spec/acceptance/clustering_spec.rb, templates/rabbitmqadmin.conf.epp
This was removed by mistake previously.
=> metadata.json: re-add Puppet 8 support

lib/puppet/provider/rabbitmq_cluster/rabbitmqctl.rb, metadata.json, spec/acceptance/clustering_spec.rb, templates/rabbitmqadmin.conf.epp
=> puppetlabs/stdlib: Allow 9.x

manifests/install/rabbitmqadmin.pp
Resolve deprecation errors by using `ensure_packages()` from stdlib vs. from Puppet
```
Warning: This function is deprecated, please use stdlib::ensure_packages instead. at ["/etc/puppetlabs/code/environments/production/modules/rabbitmq/manifests/install/rabbitmqadmin.pp", 14]:["/etc/puppetlabs/code/environments/production/modules/rabbitmq/manifests/init.pp", 574]
```
=> Use ensure_packages from stdlib

templates/rabbitmq.config.epp
Fix cluster config when `cluster_nodes` is empty
Followup to #978
=> Handle rabbitmq.config when cluster_nodes is empty

README.md, REFERENCE.md, manifests/init.pp
Allow an option to restore epel as a true soft dependency. Defaulting to `true` so that the tests will work with default behavior.
IMO, the safer / better / not technically breaking behavior would be to default this to `false`, however I don't think it's possible / trivial to do this while keeping the default class inclusion test in 
https://github.com/voxpupuli/puppet-rabbitmq/blob/137edeedf1f15e04d239a026e119c114eb2021ba/spec/acceptance/class_spec.rb#L18
as-is? If we want to try instantiating it differently there, I can rework this or open a new one.
Since there wasn't already a unit test for this, I didn't add one here, but can do so if needed depending on which option we go with.
Fixes #995
Closes #998
=> Add require_epel parameter, defaulting to `true`

lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
As noted in #970, `consumer-timeout` is another setting which has to be set as an unquoted integer in the passthrough to RabbitMQ
Rather than add more copy-paste, update the type code to use a constant that's a list of values that need to be converted to integers in a generic way.
Fixes #970
=> Add support for policy definition consumer-timeout

CHANGELOG.md, metadata.json
Includes
- #997
- #991 
- #993 
- #990 
- #994
=> Release 13.5.0

metadata.json
With the changes made in https://github.com/voxpupuli/puppet-rabbitmq/pull/982, this module needs `puppet-systemd` >= 6.0.0, as this is the first release with the `Limits` moved to the `Systemd::Unit::Service` data type. Otherwise, it's not possible to set limits, as validation will fail
=> require puppet/systemd >= 6.0.0

spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.epp
Fix indentation of `cluster_nodes` in `rabbitmq.config`. 
_This is just realigning things after upgrading recently and noticed the change from erb to epp templates, and subsequent conditional added [here](https://github.com/voxpupuli/puppet-rabbitmq/commit/aaa46bea9465934f0da2b170253c8e20e293142d) changed the alignment_
Correctly aligns `cluster_nodes` when empty...
```
--- /etc/rabbitmq/rabbitmq.config	2024-05-29 20:04:23.109445139 +0000
+++ /tmp/puppet-file20240529-12718-1ikruem	2024-05-29 20:16:08.230884643 +0000
@@ -5,8 +5,7 @@
{rabbit, [
{loopback_users, []},
{auth_backends, [rabbit_auth_backend_internal, rabbit_auth_backend_oauth2]},
-        {cluster_nodes, {[], disc}},
-
+    {cluster_nodes, {[], disc}},
{cluster_partition_handling, pause_minority},
{tcp_listen_options, [ …
```
=> Fix indentation for cluster_nodes

data/family/Debian.yaml, metadata.json, spec/classes/rabbitmq_spec.rb
Add metadata support for Debian 11, and use the "python3" package for the entire Debian family. This appears to be valid for both currently supported versions
Closes #1008
=> Add support for Debian 11

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.epp
Adds the possibility  to use cowboy_opts configuration in the rabbitmq.config.
Unfortunately, i can't test the ssl/cowboy_opts part on my side.
=> Add support for cowboy_opts config in rabbitmq.config

lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
Add `queue-version` to the list of items that should be converted from string to integer before being passed to RabbitMQ
Fixes #1017
=> Convert `queue-version` to integer

CHANGELOG.md, metadata.json
Release 13.7.0
Contains
- #1013 
- #1015  
- #1012 
- #1019
=> Release 13.7.0

.sync.yml, spec/classes/rabbitmq_spec.rb, spec/spec_helper.rb
Set `facterdb_string_keys` to `true` and update to string versions of facts in our spec tests.
Update `.sync.yml` so that modulesync doesn't override this while the default is still `false`
=> Switch to string vs. symbols for facts in spec tests

REFERENCE.md, manifests/init.pp, spec/acceptance/clustering_spec.rb, spec/classes/rabbitmq_spec.rb
* Require package_apt_pin to be a non-empty string or number
* Use `nil` instead of empty string in test for empty pin
Resolves a test failure that seems to have cropped up since the last time tests ran (probably a new version of the apt module).
This is technically breaking in a minor way, though guessing we don't need to cut a major for it. Alternately, I could continue to be less strict in the module's validation, and just update the test case 🤷 
```
3) rabbitmq on ubuntu-20.04-x86_64 with no pin it sets up an apt::source is expected to contain Apt::Source[rabbitmq] with location => "https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu", repos => "main" and key => "{\"id\"=>\"8C695B0219AFDEB04A058ED8F4E789204D206F89\", \"source\"=>\"https://packagecloud.io/rabbitmq/rabbitmq-server/gp …
```
=> Disallow empty string in `package_apt_pin`

metadata.json, spec/spec_helper_acceptance.rb
Drop metadata support for EOL OSes
- Drop support for Debian 10
- Drop support for Ubuntu 18.04
- Drop support for FreeBSD 12
- Remove some workarounds / hacks specific to older Debian-based systems.
~Note: we could / should theoretically drop support for CentOS / RHEL 7, but tests still don't function on 8 or 9.~ See #1027 for RHEL changes
=> Drop support for Debian 10, Ubuntu 18, and FreeBSD 12

.fixtures.yml, REFERENCE.md, manifests/init.pp, metadata.json, spec/classes/rabbitmq_spec.rb, spec/spec_helper_acceptance.rb
- Remove support for CentOS / RHEL 7 (breaking change)
- Remove workarounds specific to EPEL and `require_epel` parameter (breaking change)
- Add support for CentOS / RHEL 9 in metadata
- Where `repos_ensure` is not set, install `centos-release-rabbitmq-38` to support installing RabbitMQ from semi-official source (this is especially critical until #926 or something like it comes, since our tests, and the module, won't function, without this).
- Add in some additional tests for coverage (followup to #1028) that were hard to test without a supported RedHat family OS in metadata
Fixes #816
=> Add support for CentOS / RHEL 9 and drop support for 7

REFERENCE.md, data/os/CentOS.yaml, manifests/init.pp, spec/classes/rabbitmq_spec.rb
Add an `enable_centos_release` parameter, defaulting to `false`, except on CentOS, where it defaults to `true`. If enabled on any OS in the RedHat family when `repos_ensure` is also disabled, it controls adding the `centos-release-rabbitmq` package (currently
`centos-release-rabbitmq-38`)
Fixes #1033
Closes #1032
=> Add `enable_centos_release` parameter

REFERENCE.md, manifests/config.pp, manifests/init.pp, spec/classes/rabbitmq_spec.rb
… hash input
- Add support for any "Service" Systemd Parameter via drop-in
- Do not conflict with the current two statically configured parameters oom score, and openfiles
- Takes a hash - remains flexible to allow "any" service parameter needed to be set in SystemD for RabbitMQ.
<!--
Fixes #1043
=> (#1043) - Add support for any necessary systemd system parameters via hash input

lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb, lib/puppet/provider/rabbitmq_queue/rabbitmqadmin.rb, spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_exchange/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_queue/rabbitmqadmin_spec.rb
See #1053 for a clear description of the issue. This PR fix arguments parsing and uniqueness while managing rabbitmq binding with puppet
Fixes #1053
=> Fix binding arguments parsing and uniqueness in rabbitmq_binding provider

manifests/config.pp, metadata.json
The existing functions were deprecated in favor of the stdlib namespace functions in puppetlabs-stdlib 9.0.0 .
This fixes the outdated lower bound of pupetlabs-stdlib, because the namespace has already been used since [1] was mereged.
[1] d076fb25d440dd4becc0cec66065e004cae3f052
N/A
=> Use namespace function from stdlib

metadata.json
Bump upper cap of puppet-systemd to allow 9.x . The latest version at the time of writing is 9.0.1 .
N/A
=> puppet/systemd: allow 9.x
