voxpupuli/puppet-rabbitmq

README.md, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
Rebase of #305 plus added documentation
=> Make LDAP section more configurable

manifests/config.pp, manifests/init.pp, manifests/params.pp, templates/default.erb
Based on #215 with the updated suggestions.
=> Added ulimit support

manifests/params.pp
Reverts puppetlabs/puppetlabs-rabbitmq#303
=> Revert "Make $rabbitmq::params::package_apt_pin default to undef"

README.md, manifests/init.pp, spec/classes/rabbitmq_spec.rb
There were no docs or tests, and the validation failed if an integer was
passed
=> Fixes for file_limit

README.md, lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb, lib/puppet/type/rabbitmq_exchange.rb, spec/unit/puppet/provider/rabbitmq_exchange/rabbitmqadmin_spec.rb, spec/unit/puppet/type/rabbitmq_exchange_spec.rb
Added capability to use 'durable', 'internal' and 'auto_delete' options with exchanges
=> Added parameters to exchanges

spec/classes/rabbitmq_spec.rb
This will resolve test failures on master so #333 can be merged.
=> Fixing test failures due to regex matching string start.

manifests/repo/apt.pp, metadata.json, spec/classes/rabbitmq_spec.rb
=> Added full fingerprint to be compliant with puppetlabs-apt v1.8

templates/rabbitmq.config.erb
Resubmit #326. Local tests passed. Waiting for Travis CI.
Thanks @eimirae.
=> Add new line in ssl options

lib/puppet/provider/rabbitmq_binding/rabbitmqadmin.rb, spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb
There are the parameter properties_key in the
rabbitmqadmin command line missing
=> Add missing parameter for absent binding

CHANGELOG.md, metadata.json
=> Release Prep 5.2.1

lib/puppet/provider/rabbitmq_exchange/rabbitmqadmin.rb, spec/acceptance/rabbitmqadmin_spec.rb, spec/acceptance/zz281_spec.rb
Found three distinct issues causing acceptance tests to fail on Ubuntu, fixes are captured in this PR.
=> Fix acceptance tests

lib/puppet/type/rabbitmq_exchange.rb
Made some properties have default values
=> Made some properties have default values

spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
MODULES-1871 - Added default values to tcp_listen_options
=> MODULES-1871 - Added default values to tcp_listen_options

manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb
The fix was not correct, and was missing test for invalid values.
=> Fix for fixes for file_limit

README.md, manifests/config.pp, manifests/init.pp, manifests/install/rabbitmqadmin.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb, templates/rabbitmqadmin.conf.erb
- If ssl is enabled you can disable the ssl for managment explicitly
- add unit test for managment_ssl param
MODULES-1974
=> Add parameter to disable ssl for management

CHANGELOG.md, metadata.json
=> Prep 5.3.0

manifests/install.pp
This PR takes over the work in #405
=> Updates install.pp to ensure that mnesia_base directory exists.

README.md, metadata.json, spec/spec_helper_acceptance.rb
This was recently updated, but with the wrong name.
Closes #446
=> Fix dependency name

spec/acceptance/parameter_spec.rb
=> [MODULES-2281] Add acceptance tests for rabbitmq_parameter

.sync.yml, .travis.yml, spec/acceptance/zz281_spec.rb, spec/spec_helper_acceptance.rb
Also adds travis-ci jobs to run acceptance tests.
=> (maint) Fixes acceptance tests for centos7 and v3+

manifests/config.pp, spec/spec_helper_local.rb
This merges #535 and fixes unit tests.
=> Fix unit tests on #535

manifests/config.pp, manifests/install.pp, spec/classes/rabbitmq_spec.rb
I'm happy if someone wants to rework one of those too, but I think this accomplishes the important parts of #533 and #454
=> Update file / directory permissions

manifests/install/rabbitmqadmin.pp, spec/classes/rabbitmq_spec.rb
Having username:password@hostname gives an error when the password contains an "@", as in my case.
=> moved username:password to separate parameter

README.md, manifests/config.pp, manifests/init.pp, manifests/install/rabbitmqadmin.pp, manifests/params.pp, spec/acceptance/class_spec.rb, spec/classes/rabbitmq_spec.rb, templates/rabbitmq-env.conf.erb, templates/rabbitmq.config.erb
switch to optional types and use undef instead of the string `'UNSET'` in various places.
Need to fix an issue with the template rendering
=> Switch from 'UNSET' to undefs, rename management_ip to management_ip_address

lib/puppet/provider/rabbitmq_user_permissions/rabbitmqctl.rb
=> Rubocop fixes: Update hash syntax and some formatting

spec/classes/rabbitmq_spec.rb
This might be easier to read/maintain and make rubocop happier.
cc @wyardley
=> Rewrite the spec testing case

README.md, metadata.json
Update dependencies, name, and required Puppet version
=> Update dependencies, name, and required Puppet version

.fixtures.yml
Update fixtures (I think this is correct)...
=> Update fixtures to voxpupuli/archive (from puppet-community)

spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_exchange/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_plugin/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_policy/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_queue/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_user/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_user_permissions/rabbitmqctl_spec.rb, spec/unit/puppet/provider/rabbitmq_vhost/rabbitmqctl_spec.rb
This resolves the issues I was having with running the rspec tests locally.
=> Update 'require' statements and mock types to fix spec tests

README.md
This just adds back a few examples mistakenly removed in #562
=> Add back a few examples removed in #562

manifests/config.pp, manifests/init.pp, manifests/params.pp, spec/classes/rabbitmq_spec.rb, templates/rabbitmq.config.erb
I haven't added tests yet, but wanted to throw this up to see how this proposed fix looks.
=> BREAKING: Adds config_ranch parameter (default: true) to suppress config lines (#618)

lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
Quick fix for #557 (@zhianliu)
=> add support for max-length-bytes as an integer (#557), patch by zhianliu

CHANGELOG.md, metadata.json
=> Hotfix Release 5.6.1

README.md, examples/erlang_deps.pp, examples/full.pp, examples/plugin.pp, examples/server.pp, examples/service.pp, examples/site.pp, manifests/init.pp, manifests/install/rabbitmqadmin.pp, manifests/server.pp, spec/acceptance/parameter_spec.rb, spec/acceptance/policy_spec.rb, spec/acceptance/queue_spec.rb, spec/acceptance/user_spec.rb, spec/acceptance/vhost_spec.rb
=> Switch back to "include foo" (without leading colons) syntax

CHANGELOG.md, metadata.json
=> 7.1.0 release

metadata.json
=> Add tags to metadata

README.md
=> Update README to specify voxpupuli/archive dependency vs. staging

lib/facter/rabbitmq_nodename.rb, spec/unit/facter/util/fact_rabbitmq_nodename_spec.rb
* adds character - to regex for fact rabbitmq_nodename
* adds unit test for changed regex
=> Allow dash as valid character for regex

CHANGELOG.md, metadata.json
=> release 8.2.1

.msync.yml, .travis.yml, Gemfile, spec/spec_helper_acceptance.rb
=> modulesync 1.9.5

.sync.yml, .travis.yml, metadata.json, spec/classes/rabbitmq_spec.rb, spec/spec_helper_acceptance.rb
=> Enable acceptance tests; Add debian 9 support

manifests/install/rabbitmqadmin.pp
=> Replace is_ipv6_address with Puppet 4 native comparision

REFERENCE.md, docs/puppet_classes/rabbitmq.html, docs/puppet_classes/rabbitmq_3A_3Aparams.html, docs/puppet_classes/rabbitmq_3A_3Arepo_3A_3Aapt.html, manifests/init.pp, manifests/params.pp, manifests/repo/apt.pp, spec/classes/rabbitmq_spec.rb
=> Update APT GPG Key

REFERENCE.md, manifests/management.pp, manifests/server.pp
Per discussion in #744, document `rabbitmq::server`, just because it's so messy.
That said, I'm thinking we might want to deprecate / remove this compatibility interface?
=> Updates to rabbitmq::server docs

CHANGELOG.md, HISTORY.md
This should resolve test failures in #761 
I can rebase and re-run changelog in #760 if you want.
=> Remove trailing whitespace in HISTORY

.sync.yml
=> Make Ubuntu 18.04 persistent for modulesync

.github/PULL_REQUEST_TEMPLATE.md, .msync.yml, .travis.yml, .travis/setup.sh, Gemfile, Rakefile, metadata.json
=> modulesync 2.5.1 and drop Puppet4

.github/CONTRIBUTING.md, .msync.yml, .travis.yml, Dockerfile, Gemfile, Rakefile, examples/repo/apt.pp
=> modulesync 2.7.0

manifests/repo/apt.pp
=> Fetch domain from URL and use it as origin

manifests/init.pp
Updates plugin link in `init.pp` comments (see also #808) 
cc: @makmarius 
I believe this should be the actual source for `REFERENCE.md`
n/a
=> docs: Updates autocluster plugin link

CHANGELOG.md, REFERENCE.md, metadata.json
* Update CHANGELOG, REFERENCE and metadata for 9.1.0 release
Note: I'm not 100% sure whether the update to data-in-modules is breaking. Since #798 is not updated, and there don't _seem_ be be breaking changes based on PR descriptions, I think we can make this 9.1.0, but open to suggestions / corrections here.
n/a
=> Release 9.1.0

.msync.yml, .rubocop.yml, .travis.yml, Gemfile, Rakefile, spec/unit/puppet/type/rabbitmq_policy_spec.rb, spec/unit/puppet/type/rabbitmq_user_permissions_spec.rb
=> modulesync 2.10.0

.msync.yml, spec/spec_helper.rb
=> modulesync 2.10.1

.github/CONTRIBUTING.md, .msync.yml, .rubocop.yml, Gemfile, Rakefile, spec/spec_helper.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb, spec/unit/puppet/type/rabbitmq_user_permissions_spec.rb
=> modulesync 2.12.0

lib/puppet/provider/rabbitmq_parameter/rabbitmqctl.rb, spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_federation_spec.rb, spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb
I just fixed the bug, there should be some better unit test as well.
Fixes #832
=> Fix issue #832 - removing federation upstream

CHANGELOG.md, REFERENCE.md, metadata.json
- Release 10.0.1
I can take care of cutting the release if someone can approve this one.
=> [chore] release 10.0.1

.github/SECURITY.md, .travis.yml, Gemfile
* modulesync 2.12.0-20-g804b440
* Needed for #842
=> modulesync 2.12.0-20-g804b440

lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
This will allow `delivery-limit` to be set via policy.
Fixes: #846
=> Allow delivery-limit policy to be set

CHANGELOG.md, metadata.json
=> [chore] release 10.1.0

.msync.yml, .rubocop.yml, Gemfile, examples/erlang_deps.pp, examples/plugin.pp, examples/site.pp, manifests/config.pp, manifests/init.pp, manifests/install.pp, manifests/install/rabbitmqadmin.pp, manifests/management.pp, manifests/repo/apt.pp, manifests/repo/rhel.pp, manifests/service.pp, spec/acceptance/parameter_spec.rb, spec/acceptance/policy_spec.rb, spec/acceptance/queue_spec.rb, spec/acceptance/user_spec.rb, spec/acceptance/vhost_spec.rb, spec/unit/puppet/provider/rabbitmq_binding/rabbitmqadmin_spec.rb, spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_spec.rb, spec/unit/puppet/type/rabbitmq_user_permissions_spec.rb
=> modulesync 3.0.0 and style updates

CHANGELOG.md, REFERENCE.md, metadata.json
* remove invalid cluster_node_type 'disk' (#859)
* Ignore SELinux labels for systemd::service_limits (#856)
=> [chore] release 10.1.2

CHANGELOG.md, REFERENCE.md, metadata.json
=> release 10.2.0

CHANGELOG.md, REFERENCE.md, metadata.json
* Update changelog and metadata for 11.0.0
* Add optional variables to support SSL CRL check configuration (#869)
* Remove support for CentOS 6 (#870)
=> Release 11.0.0

metadata.json, spec/classes/rabbitmq_spec.rb
=> Enable Puppet 7 support (where applicable)

metadata.json, spec/spec_helper_acceptance.rb
also contains:
* https://github.com/voxpupuli/puppet-rabbitmq/pull/880
* https://github.com/voxpupuli/puppet-rabbitmq/pull/882
Closes #875
=> camptocamp/systemd: Allow 3.x

metadata.json
=> puppetlabs/stdlib: allow 7.x

metadata.json
* needs to be restarted after https://github.com/voxpupuli/puppet-archive/pull/438 got merged
* also contains https://github.com/voxpupuli/puppet-rabbitmq/pull/880
=> puppet/archive: Allow 5.x

metadata.json
=> Drop Puppet 5 support; require 6.1.0 / Drop RedHat 6 support

manifests/config.pp
=> puppet-lint: fix top_scope_facts warnings

.editorconfig, .github/CONTRIBUTING.md, .github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .msync.yml, .overcommit.yml, .pmtignore, .rspec, .rspec_parallel, .rubocop.yml, .yardopts, Dockerfile, Gemfile, Rakefile, lib/facter/rabbitmq_clustername.rb, lib/puppet/provider/rabbitmq_cluster/rabbitmqctl.rb, spec/classes/rabbitmq_spec.rb, spec/spec_helper.rb
=> modulesync 4.2.0

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release 12.0.0

CHANGELOG.md, REFERENCE.md, metadata.json
Release 12.0.1
Includes
- #907
- #905
=> Release 12.0.1

CHANGELOG.md, metadata.json
=> Release 12.0.2

CHANGELOG.md, REFERENCE.md, metadata.json
Release 12.1.0
Includes
- #921
- #919 
- #917
- #918
=> Release 12.1.0

REFERENCE.md, lib/puppet/type/rabbitmq_policy.rb, spec/unit/puppet/type/rabbitmq_policy_spec.rb
Add additional `applyto` options for the `rabbimq_policy` resource type.
Fixes #947
=> Add additional applyto options for policies

CHANGELOG.md, metadata.json
=> Release 13.1.0

.fixtures.yml
=> .fixtures.yml: remove legacy puppet_version constraint

CHANGELOG.md, metadata.json
https://github.com/voxpupuli/puppet-rabbitmq/pull/950
=> Release 13.1.1

CHANGELOG.md, metadata.json
Pulls in https://github.com/voxpupuli/puppet-rabbitmq/pull/958
=> Release 13.1.2

lib/puppet/provider/rabbitmq_cli.rb, lib/puppet/provider/rabbitmq_plugin/rabbitmqplugins.rb
This is a POC workaround for #961. See the commit message for technical details.
I don't know if this is the best fix or not. There's probably a better way.
Fixes #961
=> add a workaround for running with --noop or --tags

CHANGELOG.md, metadata.json
- #964 (Adds support for VHost metadata)
- #962
=> Release 13.2.0

metadata.json
=> metadata.json: Fix author

CHANGELOG.md, metadata.json
Includes
- #978 
- #975 
- #977 
- #974 
- #969 
- #980
- #915 
- #981 
- #982
=> Release 13.3.0

lib/puppet/provider/rabbitmq_cluster/rabbitmqctl.rb, metadata.json, spec/acceptance/clustering_spec.rb, spec/spec_helper_acceptance.rb, templates/rabbitmqadmin.conf.epp
=> puppetlabs/apt: Allow 9.x 

lib/puppet/provider/rabbitmq_cluster/rabbitmqctl.rb, metadata.json, spec/acceptance/clustering_spec.rb, templates/rabbitmqadmin.conf.epp
=> puppet/archive: Allow 7.x

CHANGELOG.md, metadata.json
=> Release 13.4.0

spec/classes/rabbitmq_spec.rb
Add unit test to cover cluster_nodes empty values.
Followup to https://github.com/voxpupuli/puppet-rabbitmq/pull/993
=> Add unit test to handle bug solved on PR #993

CHANGELOG.md, metadata.json
=> Release 13.5.1

.github/workflows/ci.yml, .msync.yml, .overcommit.yml, .rspec, .rspec_parallel, .rubocop.yml, Gemfile
=> modulesync 8.0.1

.github/labeler.yml, .msync.yml, Gemfile, REFERENCE.md, manifests/config.pp, manifests/init.pp, manifests/service.pp, spec/classes/rabbitmq_spec.rb
=> modulesync 9.0.0

REFERENCE.md, manifests/config.pp, manifests/init.pp, manifests/service.pp, spec/classes/rabbitmq_spec.rb
=> replace systemd fact with core fact

CHANGELOG.md, metadata.json
Release 13.6.0
Includes
- #1010 
- #1009 
- #1007
=> Release 13.6.0

metadata.json
Add support for Ubuntu 20 and 22
=> Add support for Ubuntu 20 and 22

CHANGELOG.md, metadata.json
=> Release 14.1.0

CHANGELOG.md, metadata.json
=> Release 14.2.0
